// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { BiosecurityCheck } from '../types';

export const biosecurityCheckData: BiosecurityCheck[] = [
  {
    "id": "BS-2025-05-07-001",
    "kapalId": "KAP-2505-00008",
    "petugas": "Rebeka Huels, A.Md",
    "tanggal": "2025-05-07",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-07-001"
  },
  {
    "id": "BS-2025-05-03-001",
    "kapalId": "KAP-2505-00005",
    "petugas": "Monique Rolfson Sr., A.Md",
    "tanggal": "2025-05-03",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Tidak Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Tidak Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-05-03-001"
  },
  {
    "id": "BS-2025-04-26-001",
    "kapalId": "KAP-2505-00003",
    "petugas": "Mr. Muhammad Rohan PhD, A.Md",
    "tanggal": "2025-04-26",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-26-001"
  },
  {
    "id": "BS-2025-05-05-001",
    "kapalId": "KAP-2505-00020",
    "petugas": "Sibyl Kirlin, A.Md",
    "tanggal": "2025-05-04",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-05-001"
  },
  {
    "id": "BS-2025-05-08-001",
    "kapalId": "KAP-2505-00035",
    "petugas": "Lemuel Stokes, A.Md",
    "tanggal": "2025-05-07",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Tidak Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-05-08-001"
  },
  {
    "id": "BS-2025-05-06-001",
    "kapalId": "KAP-2505-00037",
    "petugas": "Dawn Hartmann, A.Md",
    "tanggal": "2025-05-06",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Tidak Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-05-06-001"
  },
  {
    "id": "BS-2025-04-27-001",
    "kapalId": "KAP-2505-00040",
    "petugas": "Lizzie Leannon, A.Md",
    "tanggal": "2025-04-26",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-27-001"
  },
  {
    "id": "BS-2025-04-27-002",
    "kapalId": "KAP-2505-00009",
    "petugas": "Madelyn Schimmel, A.Md",
    "tanggal": "2025-04-27",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Tidak Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-27-002"
  },
  {
    "id": "BS-2025-05-03-002",
    "kapalId": "KAP-2505-00013",
    "petugas": "August Bartoletti, A.Md",
    "tanggal": "2025-05-03",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-03-002"
  },
  {
    "id": "BS-2025-04-25-001",
    "kapalId": "KAP-2505-00010",
    "petugas": "Pasquale Davis, A.Md",
    "tanggal": "2025-04-25",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-25-001"
  },
  {
    "id": "BS-2025-05-10-001",
    "kapalId": "KAP-2505-00015",
    "petugas": "Mitchell Stokes-Krajcik, A.Md",
    "tanggal": "2025-05-09",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-10-001"
  },
  {
    "id": "BS-2025-05-02-001",
    "kapalId": "KAP-2505-00019",
    "petugas": "Keanu Conroy, A.Md",
    "tanggal": "2025-05-02",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Tidak Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-05-02-001"
  },
  {
    "id": "BS-2025-04-21-001",
    "kapalId": "KAP-2505-00016",
    "petugas": "Marc Marks, A.Md",
    "tanggal": "2025-04-21",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-21-001"
  },
  {
    "id": "BS-2025-04-26-002",
    "kapalId": "KAP-2505-00033",
    "petugas": "Ms. Muriel Bogisich, A.Md",
    "tanggal": "2025-04-26",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sakit"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-26-002"
  },
  {
    "id": "BS-2025-05-07-002",
    "kapalId": "KAP-2505-00002",
    "petugas": "Kelly Pfeffer, A.Md",
    "tanggal": "2025-05-07",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-07-002"
  }
];
