// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { BiosecurityCheck } from '../types';

export const biosecurityCheckData: BiosecurityCheck[] = [
  {
    "id": "BS-2025-04-22-001",
    "kapalId": "KAP-2505-00012",
    "petugas": "Siti Kusuma, A.Md",
    "tanggal": "2025-04-22",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-22-001"
  },
  {
    "id": "BS-2025-04-30-001",
    "kapalId": "KAP-2505-00002",
    "petugas": "Diah Handoko, A.Md",
    "tanggal": "2025-04-30",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-30-001"
  },
  {
    "id": "BS-2025-05-04-001",
    "kapalId": "KAP-2505-00022",
    "petugas": "Ramadhan Harahap, A.Md",
    "tanggal": "2025-05-04",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-04-001"
  },
  {
    "id": "BS-2025-04-26-001",
    "kapalId": "KAP-2505-00039",
    "petugas": "Herman Pratama, A.Md",
    "tanggal": "2025-04-26",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-26-001"
  },
  {
    "id": "BS-2025-04-27-001",
    "kapalId": "KAP-2505-00020",
    "petugas": "Yudi Winarno, A.Md",
    "tanggal": "2025-04-27",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Tidak Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-27-001"
  },
  {
    "id": "BS-2025-04-20-001",
    "kapalId": "KAP-2505-00018",
    "petugas": "Fitri Hartono, A.Md",
    "tanggal": "2025-04-20",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-20-001"
  },
  {
    "id": "BS-2025-04-29-001",
    "kapalId": "KAP-2505-00011",
    "petugas": "Kurniawan Suryanto, A.Md",
    "tanggal": "2025-04-29",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-29-001"
  },
  {
    "id": "BS-2025-05-07-001",
    "kapalId": "KAP-2505-00032",
    "petugas": "Bagus Setyawan, A.Md",
    "tanggal": "2025-05-07",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-07-001"
  },
  {
    "id": "BS-2025-05-06-001",
    "kapalId": "KAP-2505-00027",
    "petugas": "Tuti Kuncoro, A.Md",
    "tanggal": "2025-05-06",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-06-001"
  },
  {
    "id": "BS-2025-04-25-001",
    "kapalId": "KAP-2505-00030",
    "petugas": "Wahyuni Hartono, A.Md",
    "tanggal": "2025-04-24",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-25-001"
  },
  {
    "id": "BS-2025-05-06-002",
    "kapalId": "KAP-2505-00030",
    "petugas": "Nur Prakoso, A.Md",
    "tanggal": "2025-05-06",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Tidak Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-05-06-002"
  },
  {
    "id": "BS-2025-05-09-001",
    "kapalId": "KAP-2505-00014",
    "petugas": "Aminah Hartono, A.Md",
    "tanggal": "2025-05-09",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-09-001"
  },
  {
    "id": "BS-2025-04-21-001",
    "kapalId": "KAP-2505-00006",
    "petugas": "Purnama Kusuma, A.Md",
    "tanggal": "2025-04-20",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-21-001"
  },
  {
    "id": "BS-2025-04-26-002",
    "kapalId": "KAP-2505-00024",
    "petugas": "Siti Suhendra, A.Md",
    "tanggal": "2025-04-26",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-26-002"
  },
  {
    "id": "BS-2025-05-09-002",
    "kapalId": "KAP-2505-00032",
    "petugas": "Kusuma Aprianto, A.Md",
    "tanggal": "2025-05-08",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-09-002"
  }
];
