// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { BiosecurityCheck } from '../types';

export const biosecurityCheckData: BiosecurityCheck[] = [
  {
    "id": "BS-2025-04-25-001",
    "kapalId": "KAP-2505-00001",
    "petugas": "Lestari Wahyudi, A.Md",
    "tanggal": "2025-04-25",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-25-001"
  },
  {
    "id": "BS-2025-04-24-001",
    "kapalId": "KAP-2505-00032",
    "petugas": "Melati Suhendra, A.Md",
    "tanggal": "2025-04-23",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Tidak Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sakit"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-24-001"
  },
  {
    "id": "BS-2025-04-28-001",
    "kapalId": "KAP-2505-00015",
    "petugas": "Dewi Harahap, A.Md",
    "tanggal": "2025-04-28",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-28-001"
  },
  {
    "id": "BS-2025-05-04-001",
    "kapalId": "KAP-2505-00014",
    "petugas": "Hidayat Winarno, A.Md",
    "tanggal": "2025-05-03",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-04-001"
  },
  {
    "id": "BS-2025-04-23-001",
    "kapalId": "KAP-2505-00033",
    "petugas": "Yuni Suryanto, A.Md",
    "tanggal": "2025-04-23",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-23-001"
  },
  {
    "id": "BS-2025-04-27-001",
    "kapalId": "KAP-2505-00004",
    "petugas": "Mukti Hartono, A.Md",
    "tanggal": "2025-04-27",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Kotor"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-27-001"
  },
  {
    "id": "BS-2025-04-30-001",
    "kapalId": "KAP-2505-00015",
    "petugas": "Nugroho Sasongko, A.Md",
    "tanggal": "2025-04-30",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sakit"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-30-001"
  },
  {
    "id": "BS-2025-05-09-001",
    "kapalId": "KAP-2505-00028",
    "petugas": "Rahman Ashari, A.Md",
    "tanggal": "2025-05-09",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Tidak Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-05-09-001"
  },
  {
    "id": "BS-2025-04-27-002",
    "kapalId": "KAP-2505-00038",
    "petugas": "Yusuf Nugraha, A.Md",
    "tanggal": "2025-04-27",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-27-002"
  },
  {
    "id": "BS-2025-05-02-001",
    "kapalId": "KAP-2505-00019",
    "petugas": "Hasan Kusuma, A.Md",
    "tanggal": "2025-05-02",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Tidak Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-05-02-001"
  },
  {
    "id": "BS-2025-04-25-002",
    "kapalId": "KAP-2505-00012",
    "petugas": "Budi Purnomo, A.Md",
    "tanggal": "2025-04-25",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-25-002"
  },
  {
    "id": "BS-2025-05-09-002",
    "kapalId": "KAP-2505-00031",
    "petugas": "Wibowo Firmansyah, A.Md",
    "tanggal": "2025-05-09",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-09-002"
  },
  {
    "id": "BS-2025-05-07-001",
    "kapalId": "KAP-2505-00038",
    "petugas": "Susanti Kusuma, A.Md",
    "tanggal": "2025-05-07",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-05-07-001"
  },
  {
    "id": "BS-2025-04-29-001",
    "kapalId": "KAP-2505-00030",
    "petugas": "Ratna Rahmadi, A.Md",
    "tanggal": "2025-04-28",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Bersih"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "lolos",
    "nomorSertifikat": "BS-2025-04-29-001"
  },
  {
    "id": "BS-2025-04-26-001",
    "kapalId": "KAP-2505-00003",
    "petugas": "Oktaviani Aprianto, A.Md",
    "tanggal": "2025-04-25",
    "checklist": [
      {
        "label": "1. Kebersihan Kapal",
        "hasil": "Kotor"
      },
      {
        "label": "2. Air Ballast",
        "hasil": "Sesuai"
      },
      {
        "label": "3. Alat Tangkap",
        "hasil": "Sesuai"
      },
      {
        "label": "4. Dokumen Kesehatan",
        "hasil": "Lengkap"
      },
      {
        "label": "5. Hama & Penyakit",
        "hasil": "Tidak Ditemukan"
      },
      {
        "label": "6. Limbah & Buangan",
        "hasil": "Sesuai"
      },
      {
        "label": "7. Awak Kapal",
        "hasil": "Sehat"
      }
    ],
    "hasil": "tidak_lolos",
    "nomorSertifikat": "BS-2025-04-26-001"
  }
];
