// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { HasilTangkap } from '../types';

export const hasilTangkapData: HasilTangkap[] = [
  {
    "id": "537c31a7-c1df-4f45-a115-8fa5071bda45",
    "kapalId": "KAP-2505-00039",
    "tanggal": "2025-05-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Timor",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 23,
        "jumlahEkor": 55,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 52,
        "jumlahEkor": 84,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 93,
        "jumlahEkor": 135,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 164,
        "jumlahEkor": 80,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8300000,
    "status": "verified"
  },
  {
    "id": "4fa1954e-5eca-4bac-82c5-ac7c0a2859e5",
    "kapalId": "KAP-2505-00037",
    "tanggal": "2025-04-17",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tomini",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 109,
        "jumlahEkor": 112,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 44,
        "jumlahEkor": 81,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 113,
        "jumlahEkor": 78,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 55,
        "jumlahEkor": 98,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8025000,
    "status": "verified"
  },
  {
    "id": "de7526dd-912d-4d3c-8550-52c2fd6207e4",
    "kapalId": "KAP-2505-00005",
    "tanggal": "2025-04-13",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Halmahera",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 67,
        "jumlahEkor": 134,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 173,
        "jumlahEkor": 113,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 176,
        "jumlahEkor": 81,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10400000,
    "status": "verified"
  },
  {
    "id": "786feeba-5cd6-4dc4-a08a-384fa042ec6e",
    "kapalId": "KAP-2505-00009",
    "tanggal": "2025-04-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Seram",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 26,
        "jumlahEkor": 22,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 88,
        "jumlahEkor": 37,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 174,
        "jumlahEkor": 32,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7200000,
    "status": "pending"
  },
  {
    "id": "98719a85-11c9-4687-bd9f-940eeefe0870",
    "kapalId": "KAP-2505-00002",
    "tanggal": "2025-04-10",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Jawa",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 95,
        "jumlahEkor": 84,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 132,
        "jumlahEkor": 145,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5675000,
    "status": "verified"
  },
  {
    "id": "2aa3803e-90b7-4818-a52d-1ae5b6808afa",
    "kapalId": "KAP-2505-00014",
    "tanggal": "2025-05-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tolo",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 75,
        "jumlahEkor": 60,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1875000,
    "status": "verified"
  },
  {
    "id": "e5c79d2e-6d7f-4b32-8ee9-82dea6309b1d",
    "kapalId": "KAP-2505-00025",
    "tanggal": "2025-05-09",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Flores",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 136,
        "jumlahEkor": 98,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 200,
        "jumlahEkor": 29,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 180,
        "jumlahEkor": 144,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 12900000,
    "status": "verified"
  },
  {
    "id": "17aa3005-5a8c-4345-89ff-ec302f2d9e4f",
    "kapalId": "KAP-2505-00037",
    "tanggal": "2025-05-02",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Malaka",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 54,
        "jumlahEkor": 83,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 72,
        "jumlahEkor": 98,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 99,
        "jumlahEkor": 142,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5625000,
    "status": "verified"
  },
  {
    "id": "f5a41b1b-ffd6-49c3-9434-c4cde685c10d",
    "kapalId": "KAP-2505-00025",
    "tanggal": "2025-04-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Seram",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 33,
        "jumlahEkor": 31,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 197,
        "jumlahEkor": 133,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5750000,
    "status": "verified"
  },
  {
    "id": "2ce303cd-4696-4a11-8ede-8553f59e0251",
    "kapalId": "KAP-2505-00027",
    "tanggal": "2025-05-07",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Banda",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 51,
        "jumlahEkor": 72,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 186,
        "jumlahEkor": 130,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 116,
        "jumlahEkor": 140,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 69,
        "jumlahEkor": 82,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10550000,
    "status": "verified"
  },
  {
    "id": "cbea3eb7-f59b-4ceb-a620-f956fdca28b9",
    "kapalId": "KAP-2505-00010",
    "tanggal": "2025-05-05",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tomini",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 147,
        "jumlahEkor": 106,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 102,
        "jumlahEkor": 124,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 187,
        "jumlahEkor": 139,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10900000,
    "status": "pending"
  },
  {
    "id": "dc55b81b-5d3a-4ccf-a430-bbaf907c535b",
    "kapalId": "KAP-2505-00035",
    "tanggal": "2025-04-11",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tomini",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 80,
        "jumlahEkor": 62,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 62,
        "jumlahEkor": 81,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 80,
        "jumlahEkor": 146,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5550000,
    "status": "pending"
  },
  {
    "id": "fb9a965a-d22d-45a9-8238-1da16028cf1a",
    "kapalId": "KAP-2505-00003",
    "tanggal": "2025-04-18",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Jawa",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 119,
        "jumlahEkor": 51,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 105,
        "jumlahEkor": 36,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5600000,
    "status": "verified"
  },
  {
    "id": "eb33e144-ce63-4ea5-8ec2-49a625bff5bb",
    "kapalId": "KAP-2505-00005",
    "tanggal": "2025-04-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Banda",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 157,
        "jumlahEkor": 149,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 126,
        "jumlahEkor": 114,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 67,
        "jumlahEkor": 90,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8750000,
    "status": "pending"
  },
  {
    "id": "b1045a0b-3911-43b4-b2eb-4e89377a0d5d",
    "kapalId": "KAP-2505-00019",
    "tanggal": "2025-05-07",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Halmahera",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 87,
        "jumlahEkor": 122,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 51,
        "jumlahEkor": 97,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 77,
        "jumlahEkor": 98,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 124,
        "jumlahEkor": 109,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8475000,
    "status": "pending"
  },
  {
    "id": "ac451f60-d699-484a-9f2e-41fed9e192d5",
    "kapalId": "KAP-2505-00028",
    "tanggal": "2025-04-10",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Malaka",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 191,
        "jumlahEkor": 24,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4775000,
    "status": "verified"
  },
  {
    "id": "8b0a8a63-2cbf-42ec-b56a-f91d5f1811d8",
    "kapalId": "KAP-2505-00002",
    "tanggal": "2025-05-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Jawa",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 146,
        "jumlahEkor": 99,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 31,
        "jumlahEkor": 20,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4425000,
    "status": "verified"
  },
  {
    "id": "8187aa22-a975-42e9-b5e7-77ed539a1131",
    "kapalId": "KAP-2505-00030",
    "tanggal": "2025-04-10",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Berhala",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 96,
        "jumlahEkor": 137,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 195,
        "jumlahEkor": 46,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7275000,
    "status": "pending"
  },
  {
    "id": "35c7bae7-d0ae-4d85-87fa-32b4dee40c58",
    "kapalId": "KAP-2505-00010",
    "tanggal": "2025-04-19",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Lombok",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 76,
        "jumlahEkor": 50,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 21,
        "jumlahEkor": 31,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 100,
        "jumlahEkor": 43,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 84,
        "jumlahEkor": 48,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7025000,
    "status": "pending"
  },
  {
    "id": "588c0d62-1c0e-489c-9942-d35bfb78766e",
    "kapalId": "KAP-2505-00029",
    "tanggal": "2025-04-11",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Cendrawasih",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 129,
        "jumlahEkor": 41,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 42,
        "jumlahEkor": 54,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4275000,
    "status": "verified"
  },
  {
    "id": "c1ac1dc9-c52b-4589-a1f8-321517676bfc",
    "kapalId": "KAP-2505-00034",
    "tanggal": "2025-04-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Sunda",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 198,
        "jumlahEkor": 135,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 58,
        "jumlahEkor": 79,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 131,
        "jumlahEkor": 80,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 138,
        "jumlahEkor": 90,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 13125000,
    "status": "pending"
  },
  {
    "id": "588ffbac-4d6d-44f1-8b2b-5b3e9671a192",
    "kapalId": "KAP-2505-00014",
    "tanggal": "2025-04-14",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Sulawesi",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 171,
        "jumlahEkor": 83,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 33,
        "jumlahEkor": 117,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 91,
        "jumlahEkor": 91,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 74,
        "jumlahEkor": 91,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9225000,
    "status": "verified"
  },
  {
    "id": "29c573af-9ecf-48d6-9c06-6b91f760c2ad",
    "kapalId": "KAP-2505-00008",
    "tanggal": "2025-04-14",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Sulawesi",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 54,
        "jumlahEkor": 69,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 52,
        "jumlahEkor": 119,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 68,
        "jumlahEkor": 145,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 116,
        "jumlahEkor": 104,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7250000,
    "status": "verified"
  },
  {
    "id": "3063f8ac-5e36-40b4-9026-a1eee068cd9b",
    "kapalId": "KAP-2505-00007",
    "tanggal": "2025-04-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Timor",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 87,
        "jumlahEkor": 119,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 71,
        "jumlahEkor": 51,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 124,
        "jumlahEkor": 102,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7050000,
    "status": "verified"
  },
  {
    "id": "54bcbbda-050e-432c-b358-482eb36654c5",
    "kapalId": "KAP-2505-00029",
    "tanggal": "2025-05-03",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Sulawesi",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 148,
        "jumlahEkor": 80,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 162,
        "jumlahEkor": 31,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7750000,
    "status": "verified"
  },
  {
    "id": "7b81a6fa-6b76-4cd9-a3b7-88909baf4d7b",
    "kapalId": "KAP-2505-00031",
    "tanggal": "2025-04-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Natuna",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 164,
        "jumlahEkor": 23,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 140,
        "jumlahEkor": 83,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 21,
        "jumlahEkor": 132,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8125000,
    "status": "verified"
  },
  {
    "id": "e4ec57e2-2b5d-4ba8-9add-15399b863cad",
    "kapalId": "KAP-2505-00010",
    "tanggal": "2025-04-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Seram",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 174,
        "jumlahEkor": 55,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 27,
        "jumlahEkor": 143,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 79,
        "jumlahEkor": 112,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 88,
        "jumlahEkor": 65,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9200000,
    "status": "verified"
  },
  {
    "id": "c1f5c44d-5dff-4429-85ca-0388539e59c2",
    "kapalId": "KAP-2505-00003",
    "tanggal": "2025-04-16",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Bali",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 27,
        "jumlahEkor": 74,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 84,
        "jumlahEkor": 115,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 31,
        "jumlahEkor": 21,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 3550000,
    "status": "verified"
  },
  {
    "id": "79a65c8f-777d-4b16-82b8-fd78f2535a5f",
    "kapalId": "KAP-2505-00038",
    "tanggal": "2025-05-09",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Banda",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 127,
        "jumlahEkor": 35,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 169,
        "jumlahEkor": 71,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 49,
        "jumlahEkor": 36,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 111,
        "jumlahEkor": 70,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 11400000,
    "status": "verified"
  },
  {
    "id": "c89147b4-4d95-43db-a48b-e8f2e6a71d10",
    "kapalId": "KAP-2505-00040",
    "tanggal": "2025-05-05",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Bali",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 37,
        "jumlahEkor": 135,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 25,
        "jumlahEkor": 149,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 166,
        "jumlahEkor": 148,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5700000,
    "status": "verified"
  },
  {
    "id": "c4d992b2-378f-482b-915f-0e05eaf92268",
    "kapalId": "KAP-2505-00013",
    "tanggal": "2025-05-03",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Sawu",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 20,
        "jumlahEkor": 146,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 184,
        "jumlahEkor": 30,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5100000,
    "status": "pending"
  },
  {
    "id": "9487d07a-597b-40f2-b382-cc4b781bfc55",
    "kapalId": "KAP-2505-00035",
    "tanggal": "2025-04-18",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Timor",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 73,
        "jumlahEkor": 54,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 121,
        "jumlahEkor": 93,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 167,
        "jumlahEkor": 121,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 127,
        "jumlahEkor": 142,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 12200000,
    "status": "verified"
  },
  {
    "id": "4f948d76-c6f0-44a4-a171-681414e60c9b",
    "kapalId": "KAP-2505-00007",
    "tanggal": "2025-04-29",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Banda",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 97,
        "jumlahEkor": 54,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 151,
        "jumlahEkor": 35,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 126,
        "jumlahEkor": 39,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 30,
        "jumlahEkor": 46,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10100000,
    "status": "pending"
  },
  {
    "id": "44e3a6d3-6450-4ba6-aadf-3327aeecab32",
    "kapalId": "KAP-2505-00032",
    "tanggal": "2025-05-02",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Karimata",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 125,
        "jumlahEkor": 101,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 135,
        "jumlahEkor": 31,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6500000,
    "status": "pending"
  },
  {
    "id": "c5af6d93-6eac-41ed-ac42-a9c474cad9cb",
    "kapalId": "KAP-2505-00020",
    "tanggal": "2025-04-25",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Arafura",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 182,
        "jumlahEkor": 61,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 28,
        "jumlahEkor": 39,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 146,
        "jumlahEkor": 42,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8900000,
    "status": "verified"
  },
  {
    "id": "a881ae51-2d8c-448c-8e6f-19489b9ee302",
    "kapalId": "KAP-2505-00016",
    "tanggal": "2025-05-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Berhala",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 175,
        "jumlahEkor": 110,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4375000,
    "status": "verified"
  },
  {
    "id": "405204dd-ff8b-417a-824a-0ba5e29a7b94",
    "kapalId": "KAP-2505-00035",
    "tanggal": "2025-04-28",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Malaka",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 40,
        "jumlahEkor": 104,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 175,
        "jumlahEkor": 107,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 142,
        "jumlahEkor": 112,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 107,
        "jumlahEkor": 88,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 11600000,
    "status": "verified"
  },
  {
    "id": "a704d416-6690-45ab-9f49-abd3d9b190e0",
    "kapalId": "KAP-2505-00028",
    "tanggal": "2025-05-06",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Makassar",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 150,
        "jumlahEkor": 106,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 130,
        "jumlahEkor": 53,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7000000,
    "status": "verified"
  },
  {
    "id": "e56bd1b9-5f5d-48af-a7f2-71f0547e1889",
    "kapalId": "KAP-2505-00037",
    "tanggal": "2025-04-26",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Sawu",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 26,
        "jumlahEkor": 143,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 650000,
    "status": "pending"
  },
  {
    "id": "e451d7b5-f911-4502-ba71-4fe1a562e63a",
    "kapalId": "KAP-2505-00038",
    "tanggal": "2025-04-15",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Malaka",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 77,
        "jumlahEkor": 78,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 156,
        "jumlahEkor": 61,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5825000,
    "status": "verified"
  },
  {
    "id": "d9a21d9c-1651-4047-a7cc-954d042b4a87",
    "kapalId": "KAP-2505-00039",
    "tanggal": "2025-04-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Maluku",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 118,
        "jumlahEkor": 47,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2950000,
    "status": "pending"
  },
  {
    "id": "2ef31404-45d8-43bf-a47d-4c2b3dabd0c3",
    "kapalId": "KAP-2505-00031",
    "tanggal": "2025-04-15",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Lombok",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 26,
        "jumlahEkor": 130,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 145,
        "jumlahEkor": 138,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 135,
        "jumlahEkor": 137,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 70,
        "jumlahEkor": 103,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9400000,
    "status": "verified"
  },
  {
    "id": "1c0d87c5-fdda-4252-80aa-743c576c0936",
    "kapalId": "KAP-2505-00038",
    "tanggal": "2025-05-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Sulawesi",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 28,
        "jumlahEkor": 127,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 22,
        "jumlahEkor": 125,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1250000,
    "status": "verified"
  },
  {
    "id": "2cb5139c-e1f3-4f9d-9d40-30812ec077ab",
    "kapalId": "KAP-2505-00029",
    "tanggal": "2025-04-15",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Sunda",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 53,
        "jumlahEkor": 139,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1325000,
    "status": "verified"
  },
  {
    "id": "7f4ea85e-78b0-4cd5-a1e9-b75faf6080ca",
    "kapalId": "KAP-2505-00023",
    "tanggal": "2025-04-13",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tomini",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 148,
        "jumlahEkor": 68,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 97,
        "jumlahEkor": 145,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 176,
        "jumlahEkor": 141,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10525000,
    "status": "verified"
  },
  {
    "id": "f4e84681-e9a2-44e0-8fd6-2fb0a8f32bb4",
    "kapalId": "KAP-2505-00036",
    "tanggal": "2025-04-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Seram",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 68,
        "jumlahEkor": 141,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 117,
        "jumlahEkor": 46,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4625000,
    "status": "verified"
  },
  {
    "id": "f94372e1-2666-4993-b3f9-2e01f1cbc374",
    "kapalId": "KAP-2505-00016",
    "tanggal": "2025-04-27",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Banda",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 155,
        "jumlahEkor": 124,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 107,
        "jumlahEkor": 143,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6550000,
    "status": "pending"
  },
  {
    "id": "d880355e-b057-4a69-ba1c-6062385ac302",
    "kapalId": "KAP-2505-00008",
    "tanggal": "2025-05-09",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Karimata",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 86,
        "jumlahEkor": 134,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2150000,
    "status": "verified"
  },
  {
    "id": "231fc23d-4030-4dda-964a-b41f249097d9",
    "kapalId": "KAP-2505-00008",
    "tanggal": "2025-05-02",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Arafura",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 88,
        "jumlahEkor": 73,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 116,
        "jumlahEkor": 25,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5100000,
    "status": "verified"
  },
  {
    "id": "6bd79362-a20d-4674-ac5a-773b4461d021",
    "kapalId": "KAP-2505-00039",
    "tanggal": "2025-04-14",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Lombok",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 155,
        "jumlahEkor": 123,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 89,
        "jumlahEkor": 123,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6100000,
    "status": "verified"
  },
  {
    "id": "fb46b8b6-160e-4aaa-834e-a66a08195255",
    "kapalId": "KAP-2505-00027",
    "tanggal": "2025-05-02",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Maluku",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 81,
        "jumlahEkor": 97,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 143,
        "jumlahEkor": 122,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5600000,
    "status": "verified"
  },
  {
    "id": "ba1247dd-a94a-466e-bee1-b667106c6519",
    "kapalId": "KAP-2505-00036",
    "tanggal": "2025-04-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tolo",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 191,
        "jumlahEkor": 119,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 101,
        "jumlahEkor": 56,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 109,
        "jumlahEkor": 58,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10025000,
    "status": "verified"
  },
  {
    "id": "9a75ff3e-691c-4512-a39b-369817a140ec",
    "kapalId": "KAP-2505-00010",
    "tanggal": "2025-04-25",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tomini",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 197,
        "jumlahEkor": 74,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 23,
        "jumlahEkor": 33,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 40,
        "jumlahEkor": 116,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 132,
        "jumlahEkor": 25,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9800000,
    "status": "verified"
  },
  {
    "id": "646f6dd7-fbdd-44a8-be9b-7fc3b6b5b685",
    "kapalId": "KAP-2505-00024",
    "tanggal": "2025-04-16",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Flores",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 133,
        "jumlahEkor": 42,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 22,
        "jumlahEkor": 93,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 3875000,
    "status": "verified"
  },
  {
    "id": "79f58086-ddf7-4797-a991-139fe8381236",
    "kapalId": "KAP-2505-00014",
    "tanggal": "2025-05-04",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Halmahera",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 22,
        "jumlahEkor": 78,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 160,
        "jumlahEkor": 128,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4550000,
    "status": "pending"
  },
  {
    "id": "d7b52e7b-fc74-42d8-bc88-7ad34b2c0e26",
    "kapalId": "KAP-2505-00034",
    "tanggal": "2025-04-21",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Sunda",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 97,
        "jumlahEkor": 128,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2425000,
    "status": "verified"
  },
  {
    "id": "03c2d21b-3f75-458d-89f2-6323d62f69b4",
    "kapalId": "KAP-2505-00027",
    "tanggal": "2025-04-19",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Arafura",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 31,
        "jumlahEkor": 77,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 85,
        "jumlahEkor": 55,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2900000,
    "status": "verified"
  },
  {
    "id": "177f116f-ce42-4495-ac3f-8bd7642b0127",
    "kapalId": "KAP-2505-00024",
    "tanggal": "2025-04-23",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Sulawesi",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 106,
        "jumlahEkor": 150,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 98,
        "jumlahEkor": 136,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5100000,
    "status": "verified"
  },
  {
    "id": "9d1d1e02-ed32-4d74-b341-4bbf61d47562",
    "kapalId": "KAP-2505-00003",
    "tanggal": "2025-04-24",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Jawa",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 109,
        "jumlahEkor": 31,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 76,
        "jumlahEkor": 62,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4625000,
    "status": "pending"
  },
  {
    "id": "544f0b3a-c364-47b0-8651-88efd5845dab",
    "kapalId": "KAP-2505-00011",
    "tanggal": "2025-05-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Cendrawasih",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 189,
        "jumlahEkor": 124,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 78,
        "jumlahEkor": 114,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 118,
        "jumlahEkor": 28,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9625000,
    "status": "verified"
  },
  {
    "id": "6508b0b5-0a10-493e-ae83-7d2fe7b7fd65",
    "kapalId": "KAP-2505-00007",
    "tanggal": "2025-04-19",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Sawu",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 162,
        "jumlahEkor": 100,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 79,
        "jumlahEkor": 139,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 53,
        "jumlahEkor": 59,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7350000,
    "status": "pending"
  },
  {
    "id": "a5afaa8f-7931-4c5b-9e7c-fe8654daab00",
    "kapalId": "KAP-2505-00033",
    "tanggal": "2025-04-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Banda",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 132,
        "jumlahEkor": 125,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 124,
        "jumlahEkor": 97,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 90,
        "jumlahEkor": 58,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8650000,
    "status": "verified"
  },
  {
    "id": "e955749b-2790-4199-8403-a1d3d4f8dd44",
    "kapalId": "KAP-2505-00028",
    "tanggal": "2025-04-29",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Timor",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 40,
        "jumlahEkor": 124,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 70,
        "jumlahEkor": 92,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2750000,
    "status": "verified"
  },
  {
    "id": "69fbd34e-4dcb-471c-b8b2-170654ec933e",
    "kapalId": "KAP-2505-00002",
    "tanggal": "2025-05-04",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Sunda",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 46,
        "jumlahEkor": 123,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 79,
        "jumlahEkor": 32,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 65,
        "jumlahEkor": 31,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 129,
        "jumlahEkor": 142,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7975000,
    "status": "pending"
  },
  {
    "id": "f682b805-7b4f-435e-8944-51aa3aabc5ac",
    "kapalId": "KAP-2505-00007",
    "tanggal": "2025-04-26",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Arafura",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 170,
        "jumlahEkor": 30,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 99,
        "jumlahEkor": 41,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 148,
        "jumlahEkor": 125,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10425000,
    "status": "pending"
  },
  {
    "id": "79d7d69c-480d-4d23-ad3f-a63cb730ebd8",
    "kapalId": "KAP-2505-00007",
    "tanggal": "2025-04-25",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Berhala",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 32,
        "jumlahEkor": 93,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 800000,
    "status": "verified"
  },
  {
    "id": "ff53ac98-1d7d-41ce-9157-fc92c39b4002",
    "kapalId": "KAP-2505-00024",
    "tanggal": "2025-05-02",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Karimata",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 165,
        "jumlahEkor": 53,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 75,
        "jumlahEkor": 107,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 28,
        "jumlahEkor": 113,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 105,
        "jumlahEkor": 39,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9325000,
    "status": "verified"
  },
  {
    "id": "583cdc59-38e1-4851-ae19-797956f4bcf3",
    "kapalId": "KAP-2505-00039",
    "tanggal": "2025-04-20",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Makassar",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 138,
        "jumlahEkor": 75,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 3450000,
    "status": "verified"
  },
  {
    "id": "05ce2ad6-22a1-4f9f-9127-9fc331c3bc5e",
    "kapalId": "KAP-2505-00007",
    "tanggal": "2025-04-24",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Lombok",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 164,
        "jumlahEkor": 82,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4100000,
    "status": "verified"
  },
  {
    "id": "b02abcf5-c96b-4876-8d70-9b008eb31088",
    "kapalId": "KAP-2505-00028",
    "tanggal": "2025-05-04",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Timor",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 104,
        "jumlahEkor": 75,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 166,
        "jumlahEkor": 92,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6750000,
    "status": "verified"
  },
  {
    "id": "76007266-fc94-4cc4-ba9e-1608c22bdb07",
    "kapalId": "KAP-2505-00006",
    "tanggal": "2025-04-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Arafura",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 94,
        "jumlahEkor": 66,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2350000,
    "status": "verified"
  },
  {
    "id": "38debfd5-b840-47d6-9dde-07fb0e53429e",
    "kapalId": "KAP-2505-00022",
    "tanggal": "2025-05-05",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Flores",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 22,
        "jumlahEkor": 30,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 163,
        "jumlahEkor": 77,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4625000,
    "status": "pending"
  },
  {
    "id": "db6f17a0-0abe-4195-91fe-d5efe3dc16f8",
    "kapalId": "KAP-2505-00028",
    "tanggal": "2025-04-16",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tomini",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 44,
        "jumlahEkor": 124,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 76,
        "jumlahEkor": 77,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 3000000,
    "status": "pending"
  },
  {
    "id": "0c3888a6-adad-451a-9a1b-9b8cd268ccde",
    "kapalId": "KAP-2505-00001",
    "tanggal": "2025-04-23",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Natuna",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 186,
        "jumlahEkor": 150,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 78,
        "jumlahEkor": 27,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 47,
        "jumlahEkor": 120,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 146,
        "jumlahEkor": 89,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 11425000,
    "status": "verified"
  },
  {
    "id": "904203b3-98ca-4d1c-8748-680beaf989b4",
    "kapalId": "KAP-2505-00033",
    "tanggal": "2025-04-20",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Sunda",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 169,
        "jumlahEkor": 39,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 97,
        "jumlahEkor": 133,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 119,
        "jumlahEkor": 142,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9625000,
    "status": "verified"
  },
  {
    "id": "c093d055-bc75-49f9-822a-e718e0ca0cca",
    "kapalId": "KAP-2505-00008",
    "tanggal": "2025-04-27",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Teluk Tolo",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 46,
        "jumlahEkor": 87,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 148,
        "jumlahEkor": 53,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 56,
        "jumlahEkor": 66,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 48,
        "jumlahEkor": 65,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7450000,
    "status": "pending"
  },
  {
    "id": "9f15641e-fb1a-493b-8185-bf1245ca409e",
    "kapalId": "KAP-2505-00002",
    "tanggal": "2025-04-27",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Laut Flores",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 115,
        "jumlahEkor": 67,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2875000,
    "status": "pending"
  },
  {
    "id": "18f85739-a7bc-42f8-84a2-790c6c53a5dc",
    "kapalId": "KAP-2505-00006",
    "tanggal": "2025-04-11",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Malaka",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 182,
        "jumlahEkor": 128,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 114,
        "jumlahEkor": 88,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7400000,
    "status": "pending"
  },
  {
    "id": "a58994d7-e162-4811-b6a5-42869295ccbb",
    "kapalId": "KAP-2505-00005",
    "tanggal": "2025-04-10",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Makassar",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 75,
        "jumlahEkor": 97,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 49,
        "jumlahEkor": 50,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 3100000,
    "status": "pending"
  },
  {
    "id": "2b9c6370-02df-4e68-b97e-a64beea337ec",
    "kapalId": "KAP-2505-00016",
    "tanggal": "2025-04-16",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Selat Lombok",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 22,
        "jumlahEkor": 37,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 48,
        "jumlahEkor": 20,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 115,
        "jumlahEkor": 42,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 90,
        "jumlahEkor": 65,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6875000,
    "status": "pending"
  }
];
