// Generated by scripts/seed-mock-data.ts — do not edit by hand.
export const hasilTangkapData = [
  {
    "id": "857c5e45-1d7b-45f9-8115-02a714fe1a56",
    "kapalId": "KAP-2608-00005",
    "tanggal": "2026-08-03",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Clwyd",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 121,
        "jumlahEkor": 113,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 170,
        "jumlahEkor": 141,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 100,
        "jumlahEkor": 120,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9775000,
    "status": "verified"
  },
  {
    "id": "1d9c1651-0477-4cc9-b54d-042b4a87917a",
    "kapalId": "KAP-2608-00026",
    "tanggal": "2026-08-06",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Devon",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 62,
        "jumlahEkor": 137,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 118,
        "jumlahEkor": 47,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 176,
        "jumlahEkor": 99,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 134,
        "jumlahEkor": 40,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 12250000,
    "status": "pending"
  },
  {
    "id": "4a2ef314-0445-4d83-bbf4-7d4c2b3dabd0",
    "kapalId": "KAP-2608-00006",
    "tanggal": "2026-07-15",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Dumfries and Galloway",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 145,
        "jumlahEkor": 138,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 135,
        "jumlahEkor": 137,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7000000,
    "status": "verified"
  },
  {
    "id": "b0d0c1c0-d87c-45fd-bda2-520aa743c576",
    "kapalId": "KAP-2608-00034",
    "tanggal": "2026-07-09",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Grampian",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 71,
        "jumlahEkor": 65,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1775000,
    "status": "verified"
  },
  {
    "id": "b082e2cb-5139-4ce1-8f3f-9dd4030812ec",
    "kapalId": "KAP-2608-00017",
    "tanggal": "2026-07-21",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Cornwall",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 85,
        "jumlahEkor": 45,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2125000,
    "status": "verified"
  },
  {
    "id": "1db56fde-7f4e-4a85-ae78-b0cd51e9b75f",
    "kapalId": "KAP-2608-00028",
    "tanggal": "2026-08-07",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Central",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 31,
        "jumlahEkor": 92,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 128,
        "jumlahEkor": 23,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 3975000,
    "status": "verified"
  },
  {
    "id": "190e6264-e83f-44e8-b468-1e9a24e0fd62",
    "kapalId": "KAP-2608-00021",
    "tanggal": "2026-07-30",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Crawford County",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 141,
        "jumlahEkor": 116,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 3525000,
    "status": "verified"
  },
  {
    "id": "abc7ff94-372e-4126-a669-933f92e01f1c",
    "kapalId": "KAP-2608-00022",
    "tanggal": "2026-08-01",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Marshall County",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 66,
        "jumlahEkor": 23,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 93,
        "jumlahEkor": 101,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 136,
        "jumlahEkor": 72,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 91,
        "jumlahEkor": 22,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9650000,
    "status": "verified"
  },
  {
    "id": "355eb057-a69a-41c6-8062-385ac302efa2",
    "kapalId": "KAP-2608-00011",
    "tanggal": "2026-07-18",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Fayette County",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 20,
        "jumlahEkor": 84,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 86,
        "jumlahEkor": 134,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 174,
        "jumlahEkor": 90,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 111,
        "jumlahEkor": 25,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9775000,
    "status": "pending"
  },
  {
    "id": "c23d4030-dda6-44ab-b41f-249097d96b49",
    "kapalId": "KAP-2608-00016",
    "tanggal": "2026-07-21",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan North Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 48,
        "jumlahEkor": 50,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 38,
        "jumlahEkor": 147,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2150000,
    "status": "pending"
  },
  {
    "id": "0d674c5a-773b-4446-a1d0-2182d2a5f159",
    "kapalId": "KAP-2608-00030",
    "tanggal": "2026-08-01",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Worcestershire",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 170,
        "jumlahEkor": 85,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 125,
        "jumlahEkor": 52,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 95,
        "jumlahEkor": 37,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 140,
        "jumlahEkor": 40,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 13250000,
    "status": "pending"
  },
  {
    "id": "0eaaa34e-a66a-4081-b952-550c69e9689f",
    "kapalId": "KAP-2608-00012",
    "tanggal": "2026-07-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Pike County",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 155,
        "jumlahEkor": 71,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 36,
        "jumlahEkor": 75,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4775000,
    "status": "verified"
  },
  {
    "id": "4a66eee1-b667-4106-bc65-19d1e43eaec4",
    "kapalId": "KAP-2608-00012",
    "tanggal": "2026-07-21",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Calhoun County",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 73,
        "jumlahEkor": 81,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 170,
        "jumlahEkor": 128,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 133,
        "jumlahEkor": 97,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9400000,
    "status": "verified"
  },
  {
    "id": "e691c512-39b3-4698-a17a-140ec889696d",
    "kapalId": "KAP-2608-00005",
    "tanggal": "2026-07-27",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Lawrence County",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 142,
        "jumlahEkor": 80,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 87,
        "jumlahEkor": 145,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 197,
        "jumlahEkor": 44,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10650000,
    "status": "verified"
  },
  {
    "id": "7fbdd4a8-e9b7-4fc3-bb6b-5b685f334558",
    "kapalId": "KAP-2608-00023",
    "tanggal": "2026-07-09",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan County Antrim",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 200,
        "jumlahEkor": 75,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 175,
        "jumlahEkor": 133,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9375000,
    "status": "pending"
  },
  {
    "id": "6ddf7797-9911-439f-9e83-812368cfcd24",
    "kapalId": "KAP-2608-00034",
    "tanggal": "2026-08-02",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Shropshire",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 86,
        "jumlahEkor": 92,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 26,
        "jumlahEkor": 90,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2800000,
    "status": "verified"
  },
  {
    "id": "742d8c88-7ad3-44b2-9c0e-26c618a79107",
    "kapalId": "KAP-2608-00028",
    "tanggal": "2026-07-16",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Crawford County",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 108,
        "jumlahEkor": 111,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 199,
        "jumlahEkor": 124,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7675000,
    "status": "verified"
  },
  {
    "id": "b3f7558d-9f26-4323-8d62-f69b4354794b",
    "kapalId": "KAP-2608-00032",
    "tanggal": "2026-07-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Worcestershire",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 44,
        "jumlahEkor": 34,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1100000,
    "status": "verified"
  },
  {
    "id": "116fce42-495c-43f8-8bd7-642b01279757",
    "kapalId": "KAP-2608-00036",
    "tanggal": "2026-07-19",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Lee County",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 108,
        "jumlahEkor": 148,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2700000,
    "status": "verified"
  },
  {
    "id": "d1d1e02e-d32d-4743-9414-bbf61d47562c",
    "kapalId": "KAP-2608-00020",
    "tanggal": "2026-07-13",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Worcestershire",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 78,
        "jumlahEkor": 93,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1950000,
    "status": "verified"
  },
  {
    "id": "44f0b3ac-3647-4b06-b518-8efd5845dab1",
    "kapalId": "KAP-2608-00025",
    "tanggal": "2026-07-31",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Grampian",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 164,
        "jumlahEkor": 62,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 150,
        "jumlahEkor": 91,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 31,
        "jumlahEkor": 66,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8625000,
    "status": "verified"
  },
  {
    "id": "b0b50a10-93ee-4837-bd2f-e7b7fd6585bc",
    "kapalId": "KAP-2608-00025",
    "tanggal": "2026-07-28",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Perry County",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 79,
        "jumlahEkor": 139,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 53,
        "jumlahEkor": 59,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 97,
        "jumlahEkor": 62,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 20,
        "jumlahEkor": 92,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6225000,
    "status": "verified"
  },
  {
    "id": "aa8f7931-c5be-47cf-ae86-54daab006647",
    "kapalId": "KAP-2608-00024",
    "tanggal": "2026-07-18",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan North Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 90,
        "jumlahEkor": 58,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 143,
        "jumlahEkor": 62,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 137,
        "jumlahEkor": 143,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9250000,
    "status": "verified"
  },
  {
    "id": "90199403-a1d3-4d4f-88dd-440ac60c47d4",
    "kapalId": "KAP-2608-00005",
    "tanggal": "2026-08-01",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Washington County",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 78,
        "jumlahEkor": 64,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 110,
        "jumlahEkor": 60,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 127,
        "jumlahEkor": 114,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 49,
        "jumlahEkor": 79,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9100000,
    "status": "verified"
  },
  {
    "id": "9fbd34e4-dcb7-41c8-bb21-70654ec933ed",
    "kapalId": "KAP-2608-00011",
    "tanggal": "2026-07-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Humberside",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 189,
        "jumlahEkor": 74,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4725000,
    "status": "verified"
  },
  {
    "id": "bcf682b8-057b-44f3-a5e9-4451aa3aabc5",
    "kapalId": "KAP-2608-00025",
    "tanggal": "2026-08-01",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Monroe County",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 170,
        "jumlahEkor": 30,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 99,
        "jumlahEkor": 41,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6725000,
    "status": "verified"
  },
  {
    "id": "c480dd23-d3fa-463c-ab73-0ebd8b8f69df",
    "kapalId": "KAP-2608-00012",
    "tanggal": "2026-07-30",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Bedfordshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 120,
        "jumlahEkor": 79,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 128,
        "jumlahEkor": 131,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 109,
        "jumlahEkor": 132,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 91,
        "jumlahEkor": 95,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 11200000,
    "status": "pending"
  },
  {
    "id": "f53ac981-d7d1-4ce1-b57f-c92c39b40024",
    "kapalId": "KAP-2608-00011",
    "tanggal": "2026-07-28",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Pike County",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 149,
        "jumlahEkor": 81,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 46,
        "jumlahEkor": 149,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4875000,
    "status": "pending"
  },
  {
    "id": "e1851e19-7979-456f-94bc-f3a55723dc70",
    "kapalId": "KAP-2608-00002",
    "tanggal": "2026-07-31",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Suffolk",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 61,
        "jumlahEkor": 123,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 172,
        "jumlahEkor": 122,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 86,
        "jumlahEkor": 99,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 62,
        "jumlahEkor": 86,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9525000,
    "status": "verified"
  },
  {
    "id": "fc331c3b-c5e7-47d2-9b63-176c8b02abcf",
    "kapalId": "KAP-2608-00028",
    "tanggal": "2026-07-31",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Essex",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 32,
        "jumlahEkor": 149,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 132,
        "jumlahEkor": 149,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 42,
        "jumlahEkor": 40,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 105,
        "jumlahEkor": 93,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7775000,
    "status": "verified"
  },
  {
    "id": "8eb31088-2dc8-423a-b657-6007266fc94c",
    "kapalId": "KAP-2608-00029",
    "tanggal": "2026-07-16",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Highlands and Islands",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 110,
        "jumlahEkor": 27,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 131,
        "jumlahEkor": 114,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 23,
        "jumlahEkor": 27,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6600000,
    "status": "verified"
  },
  {
    "id": "c22bdb07-f144-4873-9a01-c738debfd5b8",
    "kapalId": "KAP-2608-00037",
    "tanggal": "2026-07-09",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Cornwall",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 28,
        "jumlahEkor": 90,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 700000,
    "status": "pending"
  },
  {
    "id": "9e6d3cb7-0a2c-457d-bb6f-17a00abe1951",
    "kapalId": "KAP-2608-00017",
    "tanggal": "2026-08-05",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan South Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 194,
        "jumlahEkor": 117,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 29,
        "jumlahEkor": 141,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 81,
        "jumlahEkor": 51,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 70,
        "jumlahEkor": 37,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9350000,
    "status": "verified"
  },
  {
    "id": "0fc5a5ef-502c-4b80-8c38-88a6adad51aa",
    "kapalId": "KAP-2608-00036",
    "tanggal": "2026-07-29",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Gloucestershire",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 36,
        "jumlahEkor": 75,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 190,
        "jumlahEkor": 93,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 68,
        "jumlahEkor": 50,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 124,
        "jumlahEkor": 123,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10450000,
    "status": "pending"
  },
  {
    "id": "d8819d26-d8e9-4042-a03b-398cad1c7486",
    "kapalId": "KAP-2608-00021",
    "tanggal": "2026-07-09",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Lincolnshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 163,
        "jumlahEkor": 125,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 169,
        "jumlahEkor": 139,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 74,
        "jumlahEkor": 80,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 116,
        "jumlahEkor": 106,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 13050000,
    "status": "pending"
  },
  {
    "id": "91528b43-525c-4093-9d05-5bc759f922ae",
    "kapalId": "KAP-2608-00027",
    "tanggal": "2026-07-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Durham",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 72,
        "jumlahEkor": 52,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 83,
        "jumlahEkor": 37,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 56,
        "jumlahEkor": 44,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 184,
        "jumlahEkor": 22,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9875000,
    "status": "pending"
  },
  {
    "id": "859f1564-1efb-41a9-a3b1-85bf1245ca40",
    "kapalId": "KAP-2608-00001",
    "tanggal": "2026-08-04",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Lincoln County",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 142,
        "jumlahEkor": 50,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 123,
        "jumlahEkor": 133,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 177,
        "jumlahEkor": 23,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 31,
        "jumlahEkor": 104,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 11825000,
    "status": "verified"
  },
  {
    "id": "5739a7bc-2f84-4a27-890c-6c53a5dc007d",
    "kapalId": "KAP-2608-00008",
    "tanggal": "2026-07-17",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Norfolk",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 182,
        "jumlahEkor": 128,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 114,
        "jumlahEkor": 88,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 31,
        "jumlahEkor": 90,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 198,
        "jumlahEkor": 91,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 13125000,
    "status": "verified"
  },
  {
    "id": "7e162811-6a54-4286-8929-5ccbbf05b6ea",
    "kapalId": "KAP-2608-00013",
    "tanggal": "2026-08-02",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Lake County",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 81,
        "jumlahEkor": 86,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 131,
        "jumlahEkor": 98,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 69,
        "jumlahEkor": 132,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7025000,
    "status": "verified"
  },
  {
    "id": "652b9c63-7002-4dfe-b689-7ea64beea337",
    "kapalId": "KAP-2608-00006",
    "tanggal": "2026-08-01",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan South Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 115,
        "jumlahEkor": 42,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2875000,
    "status": "verified"
  },
  {
    "id": "fd2cef10-14c7-4717-8bf0-b3ffb0f45f78",
    "kapalId": "KAP-2608-00034",
    "tanggal": "2026-08-07",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Pike County",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 73,
        "jumlahEkor": 45,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 112,
        "jumlahEkor": 23,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 63,
        "jumlahEkor": 60,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 155,
        "jumlahEkor": 36,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10075000,
    "status": "verified"
  },
  {
    "id": "0280579e-d2ec-4840-b06c-033c33c17c9e",
    "kapalId": "KAP-2608-00010",
    "tanggal": "2026-07-30",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan County Down",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 60,
        "jumlahEkor": 110,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 167,
        "jumlahEkor": 21,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5675000,
    "status": "verified"
  },
  {
    "id": "4ac7e53a-6ca1-4475-936a-692e0f8bb5b5",
    "kapalId": "KAP-2608-00033",
    "tanggal": "2026-07-26",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Jackson County",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 98,
        "jumlahEkor": 134,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 143,
        "jumlahEkor": 129,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6025000,
    "status": "verified"
  },
  {
    "id": "31ae39ef-523a-4f7d-aaaa-5473b9357cfe",
    "kapalId": "KAP-2608-00030",
    "tanggal": "2026-08-05",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Washington County",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 93,
        "jumlahEkor": 91,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2325000,
    "status": "verified"
  },
  {
    "id": "b20c61b7-6274-4d37-b6db-05244d97d8b0",
    "kapalId": "KAP-2608-00011",
    "tanggal": "2026-07-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Gwynedd County",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 192,
        "jumlahEkor": 58,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 91,
        "jumlahEkor": 48,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7075000,
    "status": "verified"
  },
  {
    "id": "f84e5684-1ce9-48c3-8c93-f8a2dee61ddb",
    "kapalId": "KAP-2608-00016",
    "tanggal": "2026-08-02",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Cambridgeshire",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 162,
        "jumlahEkor": 85,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 194,
        "jumlahEkor": 71,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 155,
        "jumlahEkor": 47,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 79,
        "jumlahEkor": 66,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 14750000,
    "status": "verified"
  },
  {
    "id": "5216c9ae-88d2-4d82-8f33-5ea90ed2bfea",
    "kapalId": "KAP-2608-00026",
    "tanggal": "2026-07-14",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Marshall County",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 74,
        "jumlahEkor": 97,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 22,
        "jumlahEkor": 89,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2400000,
    "status": "verified"
  },
  {
    "id": "a15c6d84-b9a3-41d1-b120-84d27bb5403c",
    "kapalId": "KAP-2608-00006",
    "tanggal": "2026-07-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Johnson County",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 163,
        "jumlahEkor": 132,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 43,
        "jumlahEkor": 49,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 37,
        "jumlahEkor": 129,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 151,
        "jumlahEkor": 108,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9850000,
    "status": "verified"
  },
  {
    "id": "e2842053-1e23-4cfa-b110-0a62832d1498",
    "kapalId": "KAP-2608-00039",
    "tanggal": "2026-07-10",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Staffordshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 154,
        "jumlahEkor": 68,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 49,
        "jumlahEkor": 60,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 24,
        "jumlahEkor": 24,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 200,
        "jumlahEkor": 130,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10675000,
    "status": "verified"
  },
  {
    "id": "f47c70eb-2b91-4471-8746-b3b06d634f92",
    "kapalId": "KAP-2608-00019",
    "tanggal": "2026-07-27",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Crawford County",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 88,
        "jumlahEkor": 114,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 153,
        "jumlahEkor": 139,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 29,
        "jumlahEkor": 106,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6750000,
    "status": "verified"
  },
  {
    "id": "dac9745c-08f1-4d84-8d44-0e581644d8c3",
    "kapalId": "KAP-2608-00030",
    "tanggal": "2026-07-31",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Kent",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 108,
        "jumlahEkor": 87,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 116,
        "jumlahEkor": 46,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 62,
        "jumlahEkor": 86,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 158,
        "jumlahEkor": 74,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 11100000,
    "status": "pending"
  },
  {
    "id": "fda97f06-0130-4592-be94-72eb195efa4b",
    "kapalId": "KAP-2608-00023",
    "tanggal": "2026-07-26",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Hertfordshire",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 76,
        "jumlahEkor": 118,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 45,
        "jumlahEkor": 99,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 3025000,
    "status": "verified"
  },
  {
    "id": "1b5951c9-37c5-486d-8fb4-a20e0f461add",
    "kapalId": "KAP-2608-00005",
    "tanggal": "2026-08-04",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Derbyshire",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 147,
        "jumlahEkor": 80,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 117,
        "jumlahEkor": 148,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 63,
        "jumlahEkor": 130,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8175000,
    "status": "pending"
  },
  {
    "id": "3fceb7f9-9ace-4c37-8491-9eeb36a7e165",
    "kapalId": "KAP-2608-00037",
    "tanggal": "2026-07-12",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan County Londonderry",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 127,
        "jumlahEkor": 38,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 47,
        "jumlahEkor": 137,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4350000,
    "status": "pending"
  },
  {
    "id": "5ae8ed99-585f-473f-ad4a-958af51fa345",
    "kapalId": "KAP-2608-00024",
    "tanggal": "2026-07-17",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Marion County",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 53,
        "jumlahEkor": 23,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 145,
        "jumlahEkor": 123,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 93,
        "jumlahEkor": 79,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 191,
        "jumlahEkor": 85,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 12050000,
    "status": "pending"
  },
  {
    "id": "be25fa02-59bb-4f4d-9d20-8cf1f8b971d4",
    "kapalId": "KAP-2608-00023",
    "tanggal": "2026-07-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan West Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 77,
        "jumlahEkor": 24,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 185,
        "jumlahEkor": 124,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6550000,
    "status": "verified"
  },
  {
    "id": "cfdd9753-e971-4c08-83a9-bf1b9a75f62c",
    "kapalId": "KAP-2608-00029",
    "tanggal": "2026-08-04",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Borders",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 98,
        "jumlahEkor": 137,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 140,
        "jumlahEkor": 27,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 84,
        "jumlahEkor": 68,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 190,
        "jumlahEkor": 62,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 12800000,
    "status": "verified"
  },
  {
    "id": "55aa5964-9fac-4e29-aeaa-1e642e1fb309",
    "kapalId": "KAP-2608-00027",
    "tanggal": "2026-08-03",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Berkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 109,
        "jumlahEkor": 107,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 41,
        "jumlahEkor": 134,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 88,
        "jumlahEkor": 116,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 5950000,
    "status": "verified"
  },
  {
    "id": "b74c86de-0eee-43ef-9cb6-6c1081906b44",
    "kapalId": "KAP-2608-00020",
    "tanggal": "2026-07-26",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Powys",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 37,
        "jumlahEkor": 126,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 925000,
    "status": "verified"
  },
  {
    "id": "2b5a432e-0af3-4649-b0ac-b34f1dfa2ccc",
    "kapalId": "KAP-2608-00028",
    "tanggal": "2026-08-07",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Cumbria",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 106,
        "jumlahEkor": 111,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 146,
        "jumlahEkor": 92,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6300000,
    "status": "verified"
  },
  {
    "id": "8c3c5f23-d089-4f04-9efb-406e4f1e3764",
    "kapalId": "KAP-2608-00035",
    "tanggal": "2026-07-20",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Shropshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 139,
        "jumlahEkor": 69,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 184,
        "jumlahEkor": 23,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 156,
        "jumlahEkor": 58,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 74,
        "jumlahEkor": 24,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 13825000,
    "status": "pending"
  },
  {
    "id": "4218c65d-33aa-4042-8717-e4c2cca2d759",
    "kapalId": "KAP-2608-00016",
    "tanggal": "2026-07-30",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Bedfordshire",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 97,
        "jumlahEkor": 88,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 166,
        "jumlahEkor": 62,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6575000,
    "status": "verified"
  },
  {
    "id": "7ba8ef6f-0582-4466-820c-35af2cbfd11d",
    "kapalId": "KAP-2608-00027",
    "tanggal": "2026-08-05",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Kent",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 45,
        "jumlahEkor": 35,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1125000,
    "status": "pending"
  },
  {
    "id": "aa9e3f5f-b5af-4d92-a0dc-26e5c0d16110",
    "kapalId": "KAP-2608-00033",
    "tanggal": "2026-08-03",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Cleveland",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 151,
        "jumlahEkor": 44,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 38,
        "jumlahEkor": 128,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4725000,
    "status": "pending"
  },
  {
    "id": "1906ed19-eab9-43ac-837c-d7cd9c3b9406",
    "kapalId": "KAP-2608-00014",
    "tanggal": "2026-07-13",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Central",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 115,
        "jumlahEkor": 55,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 150,
        "jumlahEkor": 139,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 197,
        "jumlahEkor": 79,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 11550000,
    "status": "pending"
  },
  {
    "id": "89f9eda7-354b-4d81-bd1b-9dad2cc7ac08",
    "kapalId": "KAP-2608-00014",
    "tanggal": "2026-07-28",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan County Fermanagh",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 21,
        "jumlahEkor": 74,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 133,
        "jumlahEkor": 108,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 32,
        "jumlahEkor": 33,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 4650000,
    "status": "verified"
  },
  {
    "id": "a5081d30-3534-4df6-aff2-746263338391",
    "kapalId": "KAP-2608-00002",
    "tanggal": "2026-08-03",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Lee County",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 57,
        "jumlahEkor": 65,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1425000,
    "status": "pending"
  },
  {
    "id": "29ed6db6-f227-44ca-bf3c-bd82efe3af0b",
    "kapalId": "KAP-2608-00002",
    "tanggal": "2026-07-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Clwyd",
    "jenisIkan": [
      {
        "nama": "Ikan Kembung",
        "beratKg": 41,
        "jumlahEkor": 130,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1025000,
    "status": "pending"
  },
  {
    "id": "a5494e1a-18ac-4975-bfa6-a33d4756e53a",
    "kapalId": "KAP-2608-00033",
    "tanggal": "2026-07-24",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Hertfordshire",
    "jenisIkan": [
      {
        "nama": "Ikan Layang",
        "beratKg": 104,
        "jumlahEkor": 129,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 155,
        "jumlahEkor": 119,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6475000,
    "status": "pending"
  },
  {
    "id": "9a09c1a8-b3df-4ea6-8ca9-09f805f3ae63",
    "kapalId": "KAP-2608-00002",
    "tanggal": "2026-07-09",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Central",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 46,
        "jumlahEkor": 83,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Kembung",
        "beratKg": 33,
        "jumlahEkor": 98,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 160,
        "jumlahEkor": 64,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 181,
        "jumlahEkor": 55,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 10500000,
    "status": "pending"
  },
  {
    "id": "8a9b4a26-5937-478e-b695-33f048c97699",
    "kapalId": "KAP-2608-00004",
    "tanggal": "2026-07-31",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Lake County",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 34,
        "jumlahEkor": 49,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 143,
        "jumlahEkor": 20,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 89,
        "jumlahEkor": 38,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 6650000,
    "status": "verified"
  },
  {
    "id": "d777b90f-6945-46cb-a41f-20d461131c81",
    "kapalId": "KAP-2608-00033",
    "tanggal": "2026-07-29",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Tayside",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 157,
        "jumlahEkor": 27,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 79,
        "jumlahEkor": 21,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 92,
        "jumlahEkor": 79,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8200000,
    "status": "pending"
  },
  {
    "id": "348741a2-5777-4c1c-847f-eb20fc15abb0",
    "kapalId": "KAP-2608-00040",
    "tanggal": "2026-07-18",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan County Tyrone",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 95,
        "jumlahEkor": 71,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2375000,
    "status": "verified"
  },
  {
    "id": "a99fbd7e-50af-41a3-87fe-3105b515b343",
    "kapalId": "KAP-2608-00003",
    "tanggal": "2026-07-17",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Herefordshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 192,
        "jumlahEkor": 143,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 197,
        "jumlahEkor": 81,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 9725000,
    "status": "verified"
  },
  {
    "id": "2d7637da-474b-471f-a302-6e01d2bf17ad",
    "kapalId": "KAP-2608-00035",
    "tanggal": "2026-07-08",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Perry County",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 114,
        "jumlahEkor": 76,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 2850000,
    "status": "verified"
  },
  {
    "id": "904f66f8-5556-4c6c-93f0-681d5b931076",
    "kapalId": "KAP-2608-00004",
    "tanggal": "2026-07-15",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan South Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Cakalang",
        "beratKg": 132,
        "jumlahEkor": 146,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 60,
        "jumlahEkor": 84,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 162,
        "jumlahEkor": 45,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8850000,
    "status": "pending"
  },
  {
    "id": "2551b271-6f8a-4c3b-a11d-5588698c1e69",
    "kapalId": "KAP-2608-00033",
    "tanggal": "2026-07-29",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan West Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 63,
        "jumlahEkor": 125,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 1575000,
    "status": "pending"
  },
  {
    "id": "469c1337-96ac-46af-8b28-044639e0a050",
    "kapalId": "KAP-2608-00007",
    "tanggal": "2026-07-31",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan West Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tuna",
        "beratKg": 56,
        "jumlahEkor": 91,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 118,
        "jumlahEkor": 142,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Cakalang",
        "beratKg": 88,
        "jumlahEkor": 129,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 58,
        "jumlahEkor": 133,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 8000000,
    "status": "verified"
  },
  {
    "id": "26b5ed0b-6e09-41b9-acb3-814f990005ee",
    "kapalId": "KAP-2608-00034",
    "tanggal": "2026-07-22",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan West Yorkshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 51,
        "jumlahEkor": 99,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Layang",
        "beratKg": 51,
        "jumlahEkor": 143,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tongkol",
        "beratKg": 179,
        "jumlahEkor": 52,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 27,
        "jumlahEkor": 115,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7700000,
    "status": "verified"
  },
  {
    "id": "ce312744-203a-4210-aa80-0089508421d8",
    "kapalId": "KAP-2608-00028",
    "tanggal": "2026-07-24",
    "waktuMulai": "06:00",
    "waktuSelesai": "12:00",
    "lokasi": "Perairan Lincolnshire",
    "jenisIkan": [
      {
        "nama": "Ikan Tongkol",
        "beratKg": 43,
        "jumlahEkor": 71,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tuna",
        "beratKg": 200,
        "jumlahEkor": 63,
        "kondisi": "Segar"
      },
      {
        "nama": "Ikan Tenggiri",
        "beratKg": 63,
        "jumlahEkor": 104,
        "kondisi": "Segar"
      }
    ],
    "estimasiNilai": 7650000,
    "status": "verified"
  }
] as const;
