// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { JadwalSandar } from '../types';

export const jadwalSandarData: JadwalSandar[] = [
  {
    "id": "d7a1d6b5-5aa5-4964-b9fa-ce29eaa1e642",
    "kapalId": "KAP-2505-00032",
    "tanggal": "2025-05-11",
    "dermaga": "Dermaga 03",
    "waktuTiba": "15:30",
    "durasiJam": 3,
    "prioritas": "Rendah"
  },
  {
    "id": "d547341d-b74c-486d-ae0e-ee3efcb66c10",
    "kapalId": "KAP-2505-00025",
    "tanggal": "2025-05-11",
    "dermaga": "Dermaga 02",
    "waktuTiba": "15:00",
    "durasiJam": 4,
    "prioritas": "Normal"
  },
  {
    "id": "79d7b750-7bb8-42b5-aa43-2e0af36490ac",
    "kapalId": "KAP-2505-00011",
    "tanggal": "2025-05-13",
    "dermaga": "Dermaga 01",
    "waktuTiba": "10:45",
    "durasiJam": 2,
    "prioritas": "Tinggi"
  },
  {
    "id": "2cccdf89-dd2b-495a-b6e0-c4408c3c5f23",
    "kapalId": "KAP-2505-00040",
    "tanggal": "2025-05-10",
    "dermaga": "Dermaga 02",
    "waktuTiba": "15:30",
    "durasiJam": 6,
    "prioritas": "Rendah"
  },
  {
    "id": "fb406e4f-1e37-4646-b6dd-659668c54218",
    "kapalId": "KAP-2505-00012",
    "tanggal": "2025-05-15",
    "dermaga": "Dermaga 02",
    "waktuTiba": "19:45",
    "durasiJam": 3,
    "prioritas": "Rendah"
  },
  {
    "id": "042717e4-c2cc-4a2d-a759-2b59a07217ba",
    "kapalId": "KAP-2505-00027",
    "tanggal": "2025-05-23",
    "dermaga": "Dermaga 03",
    "waktuTiba": "15:15",
    "durasiJam": 6,
    "prioritas": "Rendah"
  },
  {
    "id": "246620c3-5af2-4cbf-bd11-d1fbfc4a9b21",
    "kapalId": "KAP-2505-00015",
    "tanggal": "2025-05-19",
    "dermaga": "Dermaga 02",
    "waktuTiba": "13:30",
    "durasiJam": 6,
    "prioritas": "Rendah"
  },
  {
    "id": "fb5afd92-0dc2-46e5-8c0d-16110bd6b589",
    "kapalId": "KAP-2505-00038",
    "tanggal": "2025-05-13",
    "dermaga": "Dermaga 02",
    "waktuTiba": "11:15",
    "durasiJam": 5,
    "prioritas": "Tinggi"
  },
  {
    "id": "1906ed19-eab9-43ac-837c-d7cd9c3b9406",
    "kapalId": "KAP-2505-00040",
    "tanggal": "2025-05-12",
    "dermaga": "Dermaga 02",
    "waktuTiba": "12:30",
    "durasiJam": 3,
    "prioritas": "Normal"
  },
  {
    "id": "b06aa118-9f9e-4da7-b354-bd81d1b9dad2",
    "kapalId": "KAP-2505-00031",
    "tanggal": "2025-05-21",
    "dermaga": "Dermaga 02",
    "waktuTiba": "12:30",
    "durasiJam": 5,
    "prioritas": "Rendah"
  },
  {
    "id": "a7302c35-a508-41d3-9035-34df6ff27462",
    "kapalId": "KAP-2505-00022",
    "tanggal": "2025-05-12",
    "dermaga": "Dermaga 01",
    "waktuTiba": "17:00",
    "durasiJam": 4,
    "prioritas": "Rendah"
  },
  {
    "id": "bd2b0151-d29e-4d6d-8b6f-2274caf3cbd8",
    "kapalId": "KAP-2505-00024",
    "tanggal": "2025-05-22",
    "dermaga": "Dermaga 03",
    "waktuTiba": "07:45",
    "durasiJam": 3,
    "prioritas": "Normal"
  },
  {
    "id": "bf06ed45-e7dc-4ca5-9494-e1a18ac975fa",
    "kapalId": "KAP-2505-00039",
    "tanggal": "2025-05-19",
    "dermaga": "Dermaga 01",
    "waktuTiba": "06:00",
    "durasiJam": 6,
    "prioritas": "Normal"
  },
  {
    "id": "6e53ae8a-f0df-45b4-a271-9c5e49a09c1a",
    "kapalId": "KAP-2505-00019",
    "tanggal": "2025-05-20",
    "dermaga": "Dermaga 01",
    "waktuTiba": "11:45",
    "durasiJam": 6,
    "prioritas": "Tinggi"
  },
  {
    "id": "ca909f80-5f3a-4e63-a006-d18ec713a062",
    "kapalId": "KAP-2505-00026",
    "tanggal": "2025-05-18",
    "dermaga": "Dermaga 02",
    "waktuTiba": "12:30",
    "durasiJam": 3,
    "prioritas": "Normal"
  },
  {
    "id": "593778e6-9533-4f04-b8c9-7699cc26d9b2",
    "kapalId": "KAP-2505-00007",
    "tanggal": "2025-05-20",
    "dermaga": "Dermaga 01",
    "waktuTiba": "11:15",
    "durasiJam": 2,
    "prioritas": "Normal"
  },
  {
    "id": "777b90f6-9456-4cb4-a1f2-0d461131c81b",
    "kapalId": "KAP-2505-00019",
    "tanggal": "2025-05-22",
    "dermaga": "Dermaga 03",
    "waktuTiba": "18:45",
    "durasiJam": 2,
    "prioritas": "Normal"
  },
  {
    "id": "348741a2-5777-4c1c-847f-eb20fc15abb0",
    "kapalId": "KAP-2505-00017",
    "tanggal": "2025-05-14",
    "dermaga": "Dermaga 02",
    "waktuTiba": "11:15",
    "durasiJam": 2,
    "prioritas": "Normal"
  },
  {
    "id": "fff7a99f-bd7e-450a-af1a-37fe3105b515",
    "kapalId": "KAP-2505-00028",
    "tanggal": "2025-05-12",
    "dermaga": "Dermaga 01",
    "waktuTiba": "06:00",
    "durasiJam": 2,
    "prioritas": "Normal"
  },
  {
    "id": "d13862d7-637d-4a47-b4b7-1f3026e01d2b",
    "kapalId": "KAP-2505-00027",
    "tanggal": "2025-05-11",
    "dermaga": "Dermaga 02",
    "waktuTiba": "11:30",
    "durasiJam": 6,
    "prioritas": "Normal"
  }
];
