// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { Kapal } from '../types';

export const kapalData: Kapal[] = [
  {
    "id": "KAP-2505-00001",
    "nama": "KM. Sinar Perkasa",
    "jenis": "Purse Seine",
    "gt": 95,
    "mesinPk": 123,
    "kecepatanKnot": 25,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": -8.6597,
      "lng": 115.8206
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000018"
  },
  {
    "id": "KAP-2505-00002",
    "nama": "KM. Mina Bersama",
    "jenis": "Kapal Motor",
    "gt": 86,
    "mesinPk": 56,
    "kecepatanKnot": 18,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "sandar",
    "posisi": {
      "lat": -1.554,
      "lng": 108.0847
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00003",
    "nama": "KM. Bahari Laut",
    "jenis": "Gillnet",
    "gt": 7,
    "mesinPk": 33,
    "kecepatanKnot": 13,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "perbaikan",
    "posisi": {
      "lat": -8.6396,
      "lng": 115.8725
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000028"
  },
  {
    "id": "KAP-2505-00004",
    "nama": "KM. Sumber Bahari",
    "jenis": "Longline",
    "gt": 44,
    "mesinPk": 125,
    "kecepatanKnot": 10,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "perbaikan",
    "posisi": {
      "lat": -1.8644,
      "lng": 122.4785
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000019"
  },
  {
    "id": "KAP-2505-00005",
    "nama": "KM. Sentosa Sejahtera",
    "jenis": "Kapal Motor",
    "gt": 50,
    "mesinPk": 193,
    "kecepatanKnot": 16,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "perbaikan",
    "posisi": {
      "lat": -0.5898,
      "lng": 118.516
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000056"
  },
  {
    "id": "KAP-2505-00006",
    "nama": "KM. Mina Samudra",
    "jenis": "Longline",
    "gt": 43,
    "mesinPk": 49,
    "kecepatanKnot": 8,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "sandar",
    "posisi": {
      "lat": -8.1497,
      "lng": 114.3967
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00007",
    "nama": "KM. Sumber Makmur",
    "jenis": "Kapal Tanpa Motor",
    "gt": 103,
    "mesinPk": 161,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "TPI Benoa",
    "status": "sandar",
    "posisi": {
      "lat": -7.9672,
      "lng": 120.9349
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000055"
  },
  {
    "id": "KAP-2505-00008",
    "nama": "KM. Karya Mandiri",
    "jenis": "Purse Seine",
    "gt": 18,
    "mesinPk": 232,
    "kecepatanKnot": 21,
    "pelabuhanInduk": "PPP Muncar",
    "status": "sandar",
    "posisi": {
      "lat": 2.9909,
      "lng": 109.4537
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00009",
    "nama": "KM. Mina Makmur",
    "jenis": "Longline",
    "gt": 74,
    "mesinPk": 28,
    "kecepatanKnot": 21,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "melaut",
    "posisi": {
      "lat": 3.3251,
      "lng": 99.8064
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000020"
  },
  {
    "id": "KAP-2505-00010",
    "nama": "KM. Cakrawala Sentosa",
    "jenis": "Kapal Motor",
    "gt": 16,
    "mesinPk": 132,
    "kecepatanKnot": 15,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": -5.4501,
      "lng": 112.1485
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000045"
  },
  {
    "id": "KAP-2505-00011",
    "nama": "KM. Cakrawala Sakti",
    "jenis": "Purse Seine",
    "gt": 102,
    "mesinPk": 237,
    "kecepatanKnot": 15,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "melaut",
    "posisi": {
      "lat": -4.8478,
      "lng": 129.6982
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000027"
  },
  {
    "id": "KAP-2505-00012",
    "nama": "KM. Bahari Rejeki",
    "jenis": "Kapal Tanpa Motor",
    "gt": 96,
    "mesinPk": 41,
    "kecepatanKnot": 18,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "perbaikan",
    "posisi": {
      "lat": 3.0135,
      "lng": 99.6364
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000008"
  },
  {
    "id": "KAP-2505-00013",
    "nama": "KM. Tunas Indah",
    "jenis": "Gillnet",
    "gt": 109,
    "mesinPk": 246,
    "kecepatanKnot": 12,
    "pelabuhanInduk": "TPI Benoa",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -8.6431,
      "lng": 115.8534
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000037"
  },
  {
    "id": "KAP-2505-00014",
    "nama": "KM. Bahari Bahtera",
    "jenis": "Purse Seine",
    "gt": 33,
    "mesinPk": 240,
    "kecepatanKnot": 23,
    "pelabuhanInduk": "PPP Muncar",
    "status": "perbaikan",
    "posisi": {
      "lat": 4.0802,
      "lng": 123.2379
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000001"
  },
  {
    "id": "KAP-2505-00015",
    "nama": "KM. Karya Sentosa",
    "jenis": "Gillnet",
    "gt": 29,
    "mesinPk": 183,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": 3.5603,
      "lng": 99.3862
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00016",
    "nama": "KM. Tunas Bahari",
    "jenis": "Kapal Motor",
    "gt": 27,
    "mesinPk": 37,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "PPP Muncar",
    "status": "sandar",
    "posisi": {
      "lat": 3.1845,
      "lng": 99.8714
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000012"
  },
  {
    "id": "KAP-2505-00017",
    "nama": "KM. Nusantara Sakti",
    "jenis": "Purse Seine",
    "gt": 11,
    "mesinPk": 48,
    "kecepatanKnot": 13,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -7.3191,
      "lng": 134.1078
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00018",
    "nama": "KM. Tunas Utama",
    "jenis": "Kapal Tanpa Motor",
    "gt": 70,
    "mesinPk": 217,
    "kecepatanKnot": 20,
    "pelabuhanInduk": "PPP Muncar",
    "status": "perbaikan",
    "posisi": {
      "lat": -5.4311,
      "lng": 112.0286
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000002"
  },
  {
    "id": "KAP-2505-00019",
    "nama": "KM. Sumber Sakti",
    "jenis": "Longline",
    "gt": 97,
    "mesinPk": 74,
    "kecepatanKnot": 15,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "perbaikan",
    "posisi": {
      "lat": 0.8473,
      "lng": 126.8272
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000033"
  },
  {
    "id": "KAP-2505-00020",
    "nama": "KM. Berkah Sejahtera",
    "jenis": "Purse Seine",
    "gt": 61,
    "mesinPk": 229,
    "kecepatanKnot": 16,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": -1.7545,
      "lng": 108.2209
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000011"
  },
  {
    "id": "KAP-2505-00021",
    "nama": "KM. Samudra Abadi",
    "jenis": "Kapal Tanpa Motor",
    "gt": 118,
    "mesinPk": 35,
    "kecepatanKnot": 20,
    "pelabuhanInduk": "TPI Benoa",
    "status": "melaut",
    "posisi": {
      "lat": -2.6916,
      "lng": 128.9681
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000042"
  },
  {
    "id": "KAP-2505-00022",
    "nama": "KM. Sentosa Laut",
    "jenis": "Kapal Tanpa Motor",
    "gt": 63,
    "mesinPk": 234,
    "kecepatanKnot": 14,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "perbaikan",
    "posisi": {
      "lat": -8.8807,
      "lng": 135.8212
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000004"
  },
  {
    "id": "KAP-2505-00023",
    "nama": "KM. Bintang Rejeki",
    "jenis": "Kapal Motor",
    "gt": 18,
    "mesinPk": 191,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "melaut",
    "posisi": {
      "lat": 0.1788,
      "lng": 129.0212
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000006"
  },
  {
    "id": "KAP-2505-00024",
    "nama": "KM. Mina Sejahtera",
    "jenis": "Purse Seine",
    "gt": 93,
    "mesinPk": 47,
    "kecepatanKnot": 21,
    "pelabuhanInduk": "PPP Muncar",
    "status": "perbaikan",
    "posisi": {
      "lat": -2.0104,
      "lng": 129.4344
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000014"
  },
  {
    "id": "KAP-2505-00025",
    "nama": "KM. Anugerah Rejeki",
    "jenis": "Kapal Motor",
    "gt": 81,
    "mesinPk": 99,
    "kecepatanKnot": 10,
    "pelabuhanInduk": "PPP Muncar",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -2.5219,
      "lng": 129.073
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000058"
  },
  {
    "id": "KAP-2505-00026",
    "nama": "KM. Putra Laut",
    "jenis": "Gillnet",
    "gt": 84,
    "mesinPk": 235,
    "kecepatanKnot": 22,
    "pelabuhanInduk": "PPP Muncar",
    "status": "sandar",
    "posisi": {
      "lat": -2.6266,
      "lng": 135.796
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000013"
  },
  {
    "id": "KAP-2505-00027",
    "nama": "KM. Berkah Mandiri",
    "jenis": "Kapal Motor",
    "gt": 110,
    "mesinPk": 178,
    "kecepatanKnot": 9,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "perbaikan",
    "posisi": {
      "lat": -7.3991,
      "lng": 120.4638
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00028",
    "nama": "KM. Bahari Persada",
    "jenis": "Purse Seine",
    "gt": 84,
    "mesinPk": 117,
    "kecepatanKnot": 22,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "sandar",
    "posisi": {
      "lat": 1.038,
      "lng": 126.7355
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000025"
  },
  {
    "id": "KAP-2505-00029",
    "nama": "KM. Sentosa Rejeki",
    "jenis": "Gillnet",
    "gt": 57,
    "mesinPk": 29,
    "kecepatanKnot": 11,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -0.7483,
      "lng": 118.2746
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00030",
    "nama": "KM. Harapan Sejahtera",
    "jenis": "Longline",
    "gt": 98,
    "mesinPk": 73,
    "kecepatanKnot": 12,
    "pelabuhanInduk": "PPP Muncar",
    "status": "sandar",
    "posisi": {
      "lat": -8.5715,
      "lng": 120.6931
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000017"
  },
  {
    "id": "KAP-2505-00031",
    "nama": "KM. Nusantara Makmur",
    "jenis": "Gillnet",
    "gt": 84,
    "mesinPk": 139,
    "kecepatanKnot": 14,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "perbaikan",
    "posisi": {
      "lat": -6.1672,
      "lng": 105.627
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00032",
    "nama": "KM. Bintang Laut",
    "jenis": "Purse Seine",
    "gt": 118,
    "mesinPk": 92,
    "kecepatanKnot": 25,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": 1.2932,
      "lng": 126.0661
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000032"
  },
  {
    "id": "KAP-2505-00033",
    "nama": "KM. Bahari Indah",
    "jenis": "Kapal Tanpa Motor",
    "gt": 60,
    "mesinPk": 97,
    "kecepatanKnot": 10,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "sandar",
    "posisi": {
      "lat": -6.1893,
      "lng": 105.4807
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000040"
  },
  {
    "id": "KAP-2505-00034",
    "nama": "KM. Harapan Bahtera",
    "jenis": "Kapal Motor",
    "gt": 90,
    "mesinPk": 164,
    "kecepatanKnot": 9,
    "pelabuhanInduk": "PPP Muncar",
    "status": "melaut",
    "posisi": {
      "lat": -9.9989,
      "lng": 127.3681
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2505-00035",
    "nama": "KM. Mina Rejeki",
    "jenis": "Purse Seine",
    "gt": 107,
    "mesinPk": 191,
    "kecepatanKnot": 23,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "perbaikan",
    "posisi": {
      "lat": -9.3938,
      "lng": 122.2056
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000003"
  },
  {
    "id": "KAP-2505-00036",
    "nama": "KM. Putra Sakti",
    "jenis": "Gillnet",
    "gt": 79,
    "mesinPk": 188,
    "kecepatanKnot": 17,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "perbaikan",
    "posisi": {
      "lat": -8.1626,
      "lng": 134.7251
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000021"
  },
  {
    "id": "KAP-2505-00037",
    "nama": "KM. Cakrawala Indah",
    "jenis": "Purse Seine",
    "gt": 12,
    "mesinPk": 82,
    "kecepatanKnot": 17,
    "pelabuhanInduk": "PPP Muncar",
    "status": "melaut",
    "posisi": {
      "lat": -9.8494,
      "lng": 121.9486
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000007"
  },
  {
    "id": "KAP-2505-00038",
    "nama": "KM. Anugerah Sentosa",
    "jenis": "Longline",
    "gt": 108,
    "mesinPk": 239,
    "kecepatanKnot": 13,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "sandar",
    "posisi": {
      "lat": -8.1379,
      "lng": 114.4096
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000029"
  },
  {
    "id": "KAP-2505-00039",
    "nama": "KM. Cakrawala Bersama",
    "jenis": "Gillnet",
    "gt": 118,
    "mesinPk": 151,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "PPP Muncar",
    "status": "sandar",
    "posisi": {
      "lat": -7.9209,
      "lng": 134.4214
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2505-000009"
  },
  {
    "id": "KAP-2505-00040",
    "nama": "KM. Samudra Sejati",
    "jenis": "Purse Seine",
    "gt": 46,
    "mesinPk": 183,
    "kecepatanKnot": 10,
    "pelabuhanInduk": "TPI Benoa",
    "status": "melaut",
    "posisi": {
      "lat": -0.5191,
      "lng": 121.8742
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2505-000005"
  }
];
