// Generated by scripts/seed-mock-data.ts — do not edit by hand.
export const kapalData = [
  {
    "id": "KAP-2608-00001",
    "nama": "KM. Bernier spanish",
    "jenis": "Gillnet",
    "gt": 119,
    "mesinPk": 247,
    "kecepatanKnot": 22,
    "pelabuhanInduk": "TPI Benoa",
    "status": "melaut",
    "posisi": {
      "lat": -5.8501,
      "lng": 122.5213
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000001"
  },
  {
    "id": "KAP-2608-00002",
    "nama": "KM. Price cool",
    "jenis": "Gillnet",
    "gt": 54,
    "mesinPk": 130,
    "kecepatanKnot": 19,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "sandar",
    "posisi": {
      "lat": 2.014,
      "lng": 111.6614
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000030"
  },
  {
    "id": "KAP-2608-00003",
    "nama": "KM. Batz glass",
    "jenis": "Kapal Motor",
    "gt": 92,
    "mesinPk": 216,
    "kecepatanKnot": 13,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -1.5442,
      "lng": 115.7394
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000038"
  },
  {
    "id": "KAP-2608-00004",
    "nama": "KM. Collier selfish",
    "jenis": "Kapal Tanpa Motor",
    "gt": 108,
    "mesinPk": 223,
    "kecepatanKnot": 10,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "melaut",
    "posisi": {
      "lat": 5.4637,
      "lng": 115.5194
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000014"
  },
  {
    "id": "KAP-2608-00005",
    "nama": "KM. Rempel vibrant",
    "jenis": "Longline",
    "gt": 115,
    "mesinPk": 116,
    "kecepatanKnot": 19,
    "pelabuhanInduk": "PPP Muncar",
    "status": "melaut",
    "posisi": {
      "lat": 3.1437,
      "lng": 109.9063
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000055"
  },
  {
    "id": "KAP-2608-00006",
    "nama": "KM. Hammes brilliant",
    "jenis": "Gillnet",
    "gt": 11,
    "mesinPk": 39,
    "kecepatanKnot": 15,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "melaut",
    "posisi": {
      "lat": 4.6379,
      "lng": 134.1331
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2608-00007",
    "nama": "KM. Erdman kooky",
    "jenis": "Gillnet",
    "gt": 25,
    "mesinPk": 215,
    "kecepatanKnot": 15,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "melaut",
    "posisi": {
      "lat": -7.1409,
      "lng": 137.1605
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000013"
  },
  {
    "id": "KAP-2608-00008",
    "nama": "KM. Boyer wobbly",
    "jenis": "Kapal Motor",
    "gt": 47,
    "mesinPk": 130,
    "kecepatanKnot": 11,
    "pelabuhanInduk": "PPP Muncar",
    "status": "melaut",
    "posisi": {
      "lat": -5.032,
      "lng": 122.5891
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000051"
  },
  {
    "id": "KAP-2608-00009",
    "nama": "KM. Kub querulous",
    "jenis": "Kapal Motor",
    "gt": 11,
    "mesinPk": 132,
    "kecepatanKnot": 22,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "perbaikan",
    "posisi": {
      "lat": -7.4524,
      "lng": 116.7899
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000011"
  },
  {
    "id": "KAP-2608-00010",
    "nama": "KM. Ledner stained",
    "jenis": "Kapal Motor",
    "gt": 9,
    "mesinPk": 202,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "PPP Muncar",
    "status": "perbaikan",
    "posisi": {
      "lat": 4.9915,
      "lng": 113.7905
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2608-00011",
    "nama": "KM. Zulauf skeletal",
    "jenis": "Gillnet",
    "gt": 7,
    "mesinPk": 225,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "melaut",
    "posisi": {
      "lat": -0.101,
      "lng": 125.7576
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000040"
  },
  {
    "id": "KAP-2608-00012",
    "nama": "KM. Ankunding grubby",
    "jenis": "Kapal Tanpa Motor",
    "gt": 15,
    "mesinPk": 125,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "TPI Benoa",
    "status": "melaut",
    "posisi": {
      "lat": 3.6678,
      "lng": 127.318
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000004"
  },
  {
    "id": "KAP-2608-00013",
    "nama": "KM. Shanahan acclaimed",
    "jenis": "Kapal Motor",
    "gt": 27,
    "mesinPk": 81,
    "kecepatanKnot": 25,
    "pelabuhanInduk": "TPI Benoa",
    "status": "melaut",
    "posisi": {
      "lat": 3.5498,
      "lng": 112.3537
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000003"
  },
  {
    "id": "KAP-2608-00014",
    "nama": "KM. Hudson immediate",
    "jenis": "Gillnet",
    "gt": 29,
    "mesinPk": 183,
    "kecepatanKnot": 24,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": -1.9462,
      "lng": 138.7143
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2608-00015",
    "nama": "KM. Jacobs understated",
    "jenis": "Longline",
    "gt": 93,
    "mesinPk": 68,
    "kecepatanKnot": 8,
    "pelabuhanInduk": "TPI Benoa",
    "status": "melaut",
    "posisi": {
      "lat": -2.6396,
      "lng": 116.7471
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2608-00016",
    "nama": "KM. Murazik unruly",
    "jenis": "Purse Seine",
    "gt": 11,
    "mesinPk": 48,
    "kecepatanKnot": 13,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -4.7955,
      "lng": 136.7995
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000018"
  },
  {
    "id": "KAP-2608-00017",
    "nama": "KM. Legros unimportant",
    "jenis": "Gillnet",
    "gt": 103,
    "mesinPk": 182,
    "kecepatanKnot": 9,
    "pelabuhanInduk": "TPI Benoa",
    "status": "melaut",
    "posisi": {
      "lat": -1.0364,
      "lng": 129.0522
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000031"
  },
  {
    "id": "KAP-2608-00018",
    "nama": "KM. Huel steel",
    "jenis": "Longline",
    "gt": 54,
    "mesinPk": 78,
    "kecepatanKnot": 23,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "tidak_aktif",
    "posisi": {
      "lat": 3.3762,
      "lng": 123.8387
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000006"
  },
  {
    "id": "KAP-2608-00019",
    "nama": "KM. Kuhic unsteady",
    "jenis": "Gillnet",
    "gt": 118,
    "mesinPk": 212,
    "kecepatanKnot": 20,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -6.3946,
      "lng": 98.2559
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000019"
  },
  {
    "id": "KAP-2608-00020",
    "nama": "KM. Beahan-Rau wordy",
    "jenis": "Purse Seine",
    "gt": 74,
    "mesinPk": 139,
    "kecepatanKnot": 10,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "sandar",
    "posisi": {
      "lat": 5.2341,
      "lng": 127.3034
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000058"
  },
  {
    "id": "KAP-2608-00021",
    "nama": "KM. Sauer warlike",
    "jenis": "Longline",
    "gt": 34,
    "mesinPk": 215,
    "kecepatanKnot": 23,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "sandar",
    "posisi": {
      "lat": 3.4883,
      "lng": 130.0326
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000016"
  },
  {
    "id": "KAP-2608-00022",
    "nama": "KM. Casper unwelcome",
    "jenis": "Gillnet",
    "gt": 65,
    "mesinPk": 70,
    "kecepatanKnot": 23,
    "pelabuhanInduk": "PPP Muncar",
    "status": "sandar",
    "posisi": {
      "lat": -7.5616,
      "lng": 130.0093
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000010"
  },
  {
    "id": "KAP-2608-00023",
    "nama": "KM. Mertz-Zemlak kosher",
    "jenis": "Longline",
    "gt": 37,
    "mesinPk": 142,
    "kecepatanKnot": 23,
    "pelabuhanInduk": "Pelabuhan TPI Bitung",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -4.037,
      "lng": 100.7808
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2608-00024",
    "nama": "KM. Dietrich oily",
    "jenis": "Purse Seine",
    "gt": 92,
    "mesinPk": 179,
    "kecepatanKnot": 18,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "perbaikan",
    "posisi": {
      "lat": 3.1453,
      "lng": 96.3823
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000007"
  },
  {
    "id": "KAP-2608-00025",
    "nama": "KM. Lynch-Wilkinson outlandish",
    "jenis": "Longline",
    "gt": 90,
    "mesinPk": 230,
    "kecepatanKnot": 20,
    "pelabuhanInduk": "PPP Muncar",
    "status": "tidak_aktif",
    "posisi": {
      "lat": 4.6375,
      "lng": 104.6608
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000024"
  },
  {
    "id": "KAP-2608-00026",
    "nama": "KM. Collins petty",
    "jenis": "Purse Seine",
    "gt": 115,
    "mesinPk": 30,
    "kecepatanKnot": 20,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "perbaikan",
    "posisi": {
      "lat": -0.6901,
      "lng": 117.2448
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000009"
  },
  {
    "id": "KAP-2608-00027",
    "nama": "KM. MacGyver well-documented",
    "jenis": "Kapal Tanpa Motor",
    "gt": 63,
    "mesinPk": 127,
    "kecepatanKnot": 8,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "sandar",
    "posisi": {
      "lat": 1.7961,
      "lng": 110.0725
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000033"
  },
  {
    "id": "KAP-2608-00028",
    "nama": "KM. Adams self-assured",
    "jenis": "Kapal Tanpa Motor",
    "gt": 56,
    "mesinPk": 104,
    "kecepatanKnot": 22,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "melaut",
    "posisi": {
      "lat": -7.7205,
      "lng": 114.403
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000025"
  },
  {
    "id": "KAP-2608-00029",
    "nama": "KM. Kihn pretty",
    "jenis": "Purse Seine",
    "gt": 60,
    "mesinPk": 179,
    "kecepatanKnot": 17,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "sandar",
    "posisi": {
      "lat": 5.3739,
      "lng": 100.0131
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000002"
  },
  {
    "id": "KAP-2608-00030",
    "nama": "KM. Goyette robust",
    "jenis": "Purse Seine",
    "gt": 118,
    "mesinPk": 92,
    "kecepatanKnot": 25,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": -2.2816,
      "lng": 132.1783
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2608-00031",
    "nama": "KM. Bogan tepid",
    "jenis": "Gillnet",
    "gt": 42,
    "mesinPk": 58,
    "kecepatanKnot": 14,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "melaut",
    "posisi": {
      "lat": -5.9056,
      "lng": 99.7151
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2608-00032",
    "nama": "KM. Mills shimmering",
    "jenis": "Kapal Motor",
    "gt": 12,
    "mesinPk": 42,
    "kecepatanKnot": 10,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "tidak_aktif",
    "posisi": {
      "lat": -2.7202,
      "lng": 135.5775
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000035"
  },
  {
    "id": "KAP-2608-00033",
    "nama": "KM. Thompson short",
    "jenis": "Kapal Tanpa Motor",
    "gt": 92,
    "mesinPk": 241,
    "kecepatanKnot": 20,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "tidak_aktif",
    "posisi": {
      "lat": 4.4742,
      "lng": 140.6606
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000005"
  },
  {
    "id": "KAP-2608-00034",
    "nama": "KM. Reinger mean",
    "jenis": "Gillnet",
    "gt": 97,
    "mesinPk": 96,
    "kecepatanKnot": 18,
    "pelabuhanInduk": "TPI Jakarta",
    "status": "melaut",
    "posisi": {
      "lat": 4.4127,
      "lng": 130.8127
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000015"
  },
  {
    "id": "KAP-2608-00035",
    "nama": "KM. Lebsack cooperative",
    "jenis": "Longline",
    "gt": 84,
    "mesinPk": 81,
    "kecepatanKnot": 16,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "perbaikan",
    "posisi": {
      "lat": -0.8479,
      "lng": 115.2771
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": null
  },
  {
    "id": "KAP-2608-00036",
    "nama": "KM. Grant huge",
    "jenis": "Purse Seine",
    "gt": 109,
    "mesinPk": 134,
    "kecepatanKnot": 23,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": -0.2542,
      "lng": 118.0076
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000017"
  },
  {
    "id": "KAP-2608-00037",
    "nama": "KM. Harvey frank",
    "jenis": "Kapal Motor",
    "gt": 35,
    "mesinPk": 134,
    "kecepatanKnot": 17,
    "pelabuhanInduk": "PPP Muncar",
    "status": "melaut",
    "posisi": {
      "lat": -5.9843,
      "lng": 111.3969
    },
    "dokumen": {
      "siup": true,
      "slo": false,
      "pasKecil": true
    },
    "nahkodaId": "NEL-2608-000012"
  },
  {
    "id": "KAP-2608-00038",
    "nama": "KM. Lynch beloved",
    "jenis": "Kapal Tanpa Motor",
    "gt": 65,
    "mesinPk": 106,
    "kecepatanKnot": 12,
    "pelabuhanInduk": "PPI Banyuwangi",
    "status": "perbaikan",
    "posisi": {
      "lat": -4.6804,
      "lng": 95.6653
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000023"
  },
  {
    "id": "KAP-2608-00039",
    "nama": "KM. Kshlerin cruel",
    "jenis": "Gillnet",
    "gt": 103,
    "mesinPk": 166,
    "kecepatanKnot": 13,
    "pelabuhanInduk": "TPI Benoa",
    "status": "perbaikan",
    "posisi": {
      "lat": 2.3568,
      "lng": 135.3042
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000021"
  },
  {
    "id": "KAP-2608-00040",
    "nama": "KM. Harris impressionable",
    "jenis": "Longline",
    "gt": 12,
    "mesinPk": 119,
    "kecepatanKnot": 11,
    "pelabuhanInduk": "TPI Surabaya",
    "status": "sandar",
    "posisi": {
      "lat": -6.3762,
      "lng": 137.8851
    },
    "dokumen": {
      "siup": true,
      "slo": true,
      "pasKecil": false
    },
    "nahkodaId": "NEL-2608-000008"
  }
] as const;
