// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { Koperasi } from '../types';

export const koperasiData: Koperasi[] = [
  {
    "id": "43f4028b-9726-4da5-9efc-e2ac9563062b",
    "nama": "Koperasi Bahari Sejahtera",
    "lokasi": "Jakarta Utara, DKI Jakarta",
    "ketua": "Budi Santoso",
    "jumlahAnggota": 76,
    "volumeKg": 14052,
    "nilaiTransaksi": 216063480,
    "status": "Aktif"
  },
  {
    "id": "7610803e-730b-464b-b58c-0bffbee30df7",
    "nama": "Koperasi Samudra Jaya",
    "lokasi": "Tanjung Perak, Jawa Timur",
    "ketua": "Joko Susanto",
    "jumlahAnggota": 225,
    "volumeKg": 8804,
    "nilaiTransaksi": 323864575,
    "status": "Tidak Aktif"
  },
  {
    "id": "1db8c8b2-fbcb-4f36-92fb-bbcda8bfc816",
    "nama": "Koperasi Mina Mandiri",
    "lokasi": "Bitung, Sulawesi Utara",
    "ketua": "Andi Rahman",
    "jumlahAnggota": 31,
    "volumeKg": 12175,
    "nilaiTransaksi": 391967749,
    "status": "Tidak Aktif"
  },
  {
    "id": "25639678-be13-4974-be07-306f3083fed8",
    "nama": "Koperasi Laut Makmur",
    "lokasi": "Benoa, Bali",
    "ketua": "I Made Suarta",
    "jumlahAnggota": 75,
    "volumeKg": 6893,
    "nilaiTransaksi": 225478182,
    "status": "Aktif"
  },
  {
    "id": "a078dc56-7ddb-4774-8868-12feeef34bc4",
    "nama": "Koperasi Nelayan Sejati",
    "lokasi": "Belawan, Sumatera Utara",
    "ketua": "Slamet Riyadi",
    "jumlahAnggota": 94,
    "volumeKg": 13800,
    "nilaiTransaksi": 320576940,
    "status": "Aktif"
  },
  {
    "id": "e1989d45-2478-4c8c-94fe-920c284d2807",
    "nama": "Koperasi Harapan Baru",
    "lokasi": "Kendari, Sulawesi Tenggara",
    "ketua": "La Ode Hasan",
    "jumlahAnggota": 59,
    "volumeKg": 5111,
    "nilaiTransaksi": 66112734,
    "status": "Tidak Aktif"
  },
  {
    "id": "df7c2dcb-52cd-4bde-a7bc-6c4c6a7dd400",
    "nama": "Koperasi Cakrawala Bahari",
    "lokasi": "Pontianak, Kalimantan Barat",
    "ketua": "Suryadi",
    "jumlahAnggota": 229,
    "volumeKg": 11288,
    "nilaiTransaksi": 359475588,
    "status": "Tidak Aktif"
  },
  {
    "id": "d4eae453-938f-48c2-8c98-b73867131869",
    "nama": "Koperasi Tunas Bahari",
    "lokasi": "Ambon, Maluku",
    "ketua": "Abdul Latif",
    "jumlahAnggota": 119,
    "volumeKg": 13513,
    "nilaiTransaksi": 315082118,
    "status": "Aktif"
  },
  {
    "id": "22a64f1d-8edd-44af-9461-3b231ec99f0a",
    "nama": "Koperasi Mina Sejahtera",
    "lokasi": "Cirebon, Jawa Barat",
    "ketua": "Dedi Kurniawan",
    "jumlahAnggota": 232,
    "volumeKg": 5774,
    "nilaiTransaksi": 187158832,
    "status": "Tidak Aktif"
  },
  {
    "id": "90bd48ec-b8c3-4a36-a701-ac9ebe645d51",
    "nama": "Koperasi Bahari Minang",
    "lokasi": "Padang, Sumatera Barat",
    "ketua": "Zulfikar",
    "jumlahAnggota": 101,
    "volumeKg": 1474,
    "nilaiTransaksi": 276765113,
    "status": "Aktif"
  },
  {
    "id": "a8fc7f48-a7ac-4eff-9d36-5a187e39f0e7",
    "nama": "Koperasi Mitra Bahari",
    "lokasi": "Balikpapan, Kalimantan Timur",
    "ketua": "Rahmat Hidayat",
    "jumlahAnggota": 185,
    "volumeKg": 2220,
    "nilaiTransaksi": 166992196,
    "status": "Aktif"
  },
  {
    "id": "6ee741c3-8701-4355-997e-47bc07908bf9",
    "nama": "Koperasi Nusa Bahari",
    "lokasi": "Kupang, Nusa Tenggara Timur",
    "ketua": "Yohanes Bili",
    "jumlahAnggota": 194,
    "volumeKg": 7998,
    "nilaiTransaksi": 103017591,
    "status": "Aktif"
  },
  {
    "id": "d08eda0e-7fee-4c71-8108-ab31a5267d6d",
    "nama": "Koperasi Papua Bahari",
    "lokasi": "Sorong, Papua Barat Daya",
    "ketua": "Yustus Kaisiepo",
    "jumlahAnggota": 42,
    "volumeKg": 4942,
    "nilaiTransaksi": 160309034,
    "status": "Aktif"
  },
  {
    "id": "7fbe64d8-3790-4c08-965d-c908a5b8484d",
    "nama": "Koperasi Lombok Bahari",
    "lokasi": "Mataram, Nusa Tenggara Barat",
    "ketua": "Lalu Wirawan",
    "jumlahAnggota": 98,
    "volumeKg": 9172,
    "nilaiTransaksi": 105457603,
    "status": "Tidak Aktif"
  },
  {
    "id": "c871d40b-74b5-429e-960b-7f4afba692f9",
    "nama": "Koperasi Teluk Palu Sejahtera",
    "lokasi": "Palu, Sulawesi Tengah",
    "ketua": "Muhammad Yusri",
    "jumlahAnggota": 94,
    "volumeKg": 10121,
    "nilaiTransaksi": 301252465,
    "status": "Aktif"
  }
];
