// Generated by scripts/seed-mock-data.ts — do not edit by hand.
export const koperasiData = [
  {
    "id": "7610803e-730b-464b-b58c-0bffbee30df7",
    "nama": "Koperasi Strosin, Rogahn and Larkin",
    "lokasi": "Rath-Rowefort, Washington",
    "ketua": "Charlene Rohan",
    "jumlahAnggota": 232,
    "volumeKg": 11890,
    "nilaiTransaksi": 354490742,
    "status": "Aktif"
  },
  {
    "id": "8bfc8166-0cff-4256-8396-78be13974e07",
    "nama": "Koperasi Franey-Beahan - Wiegand",
    "lokasi": "Sugar Land, Nevada",
    "ketua": "Harry Osinski",
    "jumlahAnggota": 43,
    "volumeKg": 7884,
    "nilaiTransaksi": 244610103,
    "status": "Tidak Aktif"
  },
  {
    "id": "c567ddb7-7486-4812-bfee-ef34bc423ec7",
    "nama": "Koperasi Mann - Heidenreich",
    "lokasi": "West Pattymouth, South Carolina",
    "ketua": "Thalia Collier",
    "jumlahAnggota": 236,
    "volumeKg": 3549,
    "nilaiTransaksi": 225367549,
    "status": "Aktif"
  },
  {
    "id": "d2807614-0cdf-47c2-9dcb-52cdbde7bc6c",
    "nama": "Koperasi Kuhlman, Friesen and Murray",
    "lokasi": "Terryhaven, Iowa",
    "ketua": "Tess Haley",
    "jumlahAnggota": 193,
    "volumeKg": 4484,
    "nilaiTransaksi": 229549995,
    "status": "Tidak Aktif"
  },
  {
    "id": "8c2c98b7-3867-4131-b869-05ec922a64f1",
    "nama": "Koperasi Schumm Inc",
    "lokasi": "Hudsonton, Idaho",
    "ketua": "Mr. Dave Upton",
    "jumlahAnggota": 194,
    "volumeKg": 14753,
    "nilaiTransaksi": 70646304,
    "status": "Aktif"
  },
  {
    "id": "5b56f90b-d48e-4cb8-9c3a-36701ac9ebe6",
    "nama": "Koperasi Bergstrom LLC",
    "lokasi": "North Marlon, Montana",
    "ketua": "Isabell Goyette",
    "jumlahAnggota": 213,
    "volumeKg": 7865,
    "nilaiTransaksi": 289860293,
    "status": "Tidak Aktif"
  },
  {
    "id": "effd365a-187e-439f-80e7-491516ee741c",
    "nama": "Koperasi Carroll Group",
    "lokasi": "West Tim, Illinois",
    "ketua": "Presley Kuphal",
    "jumlahAnggota": 43,
    "volumeKg": 8588,
    "nilaiTransaksi": 296354844,
    "status": "Tidak Aktif"
  },
  {
    "id": "959725d0-8eda-40e7-8fee-c71108ab31a5",
    "nama": "Koperasi Homenick and Sons",
    "lokasi": "North Ginaport, Wisconsin",
    "ketua": "Hailee Stokes",
    "jumlahAnggota": 97,
    "volumeKg": 7653,
    "nilaiTransaksi": 268734140,
    "status": "Aktif"
  },
  {
    "id": "c0865dc9-08a5-4b84-a84d-5492cc871d40",
    "nama": "Koperasi Herzog Group",
    "lokasi": "Alfredcester, Mississippi",
    "ketua": "Matthew Pollich-Murray",
    "jumlahAnggota": 187,
    "volumeKg": 2950,
    "nilaiTransaksi": 396487987,
    "status": "Aktif"
  },
  {
    "id": "53ab953c-6e8b-483c-9d39-79acb575bd37",
    "nama": "Koperasi Corkery and Sons",
    "lokasi": "San Ramon, Mississippi",
    "ketua": "Lorene Franecki",
    "jumlahAnggota": 183,
    "volumeKg": 2149,
    "nilaiTransaksi": 204904430,
    "status": "Aktif"
  },
  {
    "id": "59a1edeb-6143-4912-9e68-61f3972f03e8",
    "nama": "Koperasi Pollich Group",
    "lokasi": "Cuyahoga Falls, Nevada",
    "ketua": "Dr. Brandt Langosh",
    "jumlahAnggota": 300,
    "volumeKg": 5690,
    "nilaiTransaksi": 284030171,
    "status": "Aktif"
  },
  {
    "id": "7461e32b-16fd-4432-b2c5-1e6e4c8ef283",
    "nama": "Koperasi Bosco, Hamill and Crooks",
    "lokasi": "Agnesstead, Indiana",
    "ketua": "Keara Moen",
    "jumlahAnggota": 130,
    "volumeKg": 1186,
    "nilaiTransaksi": 216630549,
    "status": "Aktif"
  },
  {
    "id": "a654caa5-dd62-4750-b91f-ad03c709da58",
    "nama": "Koperasi Lebsack - Koepp",
    "lokasi": "North Archiestead, Hawaii",
    "ketua": "Miss April Zboncak",
    "jumlahAnggota": 138,
    "volumeKg": 7108,
    "nilaiTransaksi": 120161906,
    "status": "Aktif"
  },
  {
    "id": "e897ec08-9752-491c-abeb-31f4d4d6803c",
    "nama": "Koperasi Wyman - Smitham",
    "lokasi": "Kristinboro, Maryland",
    "ketua": "Fabian Hilll",
    "jumlahAnggota": 155,
    "volumeKg": 10020,
    "nilaiTransaksi": 293057812,
    "status": "Aktif"
  },
  {
    "id": "2e4746fd-4a14-424c-82a8-5db0f9e35144",
    "nama": "Koperasi Heidenreich, Kreiger and Reichel",
    "lokasi": "Dunwoody, Arkansas",
    "ketua": "Gilberto Deckow",
    "jumlahAnggota": 144,
    "volumeKg": 2807,
    "nilaiTransaksi": 146456130,
    "status": "Aktif"
  }
] as const;
