// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { Koperasi } from '../types';

export const koperasiData: Koperasi[] = [
  {
    "id": "75f874ef-5461-4e7d-8ed9-8f8e054a4781",
    "nama": "Koperasi Bahari Sejahtera",
    "lokasi": "Jakarta Utara, DKI Jakarta",
    "ketua": "Budi Santoso",
    "jumlahAnggota": 83,
    "volumeKg": 5990,
    "nilaiTransaksi": 294882819,
    "status": "Aktif"
  },
  {
    "id": "f280d854-3f40-428b-9972-6da5efce2ac9",
    "nama": "Koperasi Samudra Jaya",
    "lokasi": "Tanjung Perak, Jawa Timur",
    "ketua": "Joko Susanto",
    "jumlahAnggota": 139,
    "volumeKg": 4174,
    "nilaiTransaksi": 71257304,
    "status": "Aktif"
  },
  {
    "id": "2b52e797-6108-403e-b730-b64b58c0bffb",
    "nama": "Koperasi Mina Mandiri",
    "lokasi": "Bitung, Sulawesi Utara",
    "ketua": "Andi Rahman",
    "jumlahAnggota": 268,
    "volumeKg": 4197,
    "nilaiTransaksi": 71708910,
    "status": "Tidak Aktif"
  },
  {
    "id": "f7eb8cd1-db8c-48b2-afbc-bf362fbbbcda",
    "nama": "Koperasi Laut Makmur",
    "lokasi": "Benoa, Bali",
    "ketua": "I Made Suarta",
    "jumlahAnggota": 223,
    "volumeKg": 14779,
    "nilaiTransaksi": 324440966,
    "status": "Aktif"
  },
  {
    "id": "1660cff2-5639-4678-8be1-3974e07306f3",
    "nama": "Koperasi Nelayan Sejati",
    "lokasi": "Belawan, Sumatera Utara",
    "ketua": "Slamet Riyadi",
    "jumlahAnggota": 173,
    "volumeKg": 4153,
    "nilaiTransaksi": 382768006,
    "status": "Tidak Aktif"
  },
  {
    "id": "d8f268aa-078d-4c56-b7dd-b77486812fee",
    "nama": "Koperasi Harapan Baru",
    "lokasi": "Kendari, Sulawesi Tenggara",
    "ketua": "La Ode Hasan",
    "jumlahAnggota": 286,
    "volumeKg": 4033,
    "nilaiTransaksi": 141803794,
    "status": "Aktif"
  },
  {
    "id": "c423ec7e-1989-4d45-a247-8c8c4fe920c2",
    "nama": "Koperasi Cakrawala Bahari",
    "lokasi": "Pontianak, Kalimantan Barat",
    "ketua": "Suryadi",
    "jumlahAnggota": 106,
    "volumeKg": 12884,
    "nilaiTransaksi": 100732560,
    "status": "Aktif"
  },
  {
    "id": "076140cd-f7c2-4dcb-a52c-dbde7bc6c4c6",
    "nama": "Koperasi Tunas Bahari",
    "lokasi": "Ambon, Maluku",
    "ketua": "Abdul Latif",
    "jumlahAnggota": 162,
    "volumeKg": 12663,
    "nilaiTransaksi": 339525624,
    "status": "Aktif"
  },
  {
    "id": "00abbeed-4eae-4453-9938-f8c2c98b7386",
    "nama": "Koperasi Mina Sejahtera",
    "lokasi": "Cirebon, Jawa Barat",
    "ketua": "Dedi Kurniawan",
    "jumlahAnggota": 48,
    "volumeKg": 4084,
    "nilaiTransaksi": 86464112,
    "status": "Aktif"
  },
  {
    "id": "6905ec92-2a64-4f1d-b8ed-d4af4613b231",
    "nama": "Koperasi Bahari Minang",
    "lokasi": "Padang, Sumatera Barat",
    "ketua": "Zulfikar",
    "jumlahAnggota": 249,
    "volumeKg": 9362,
    "nilaiTransaksi": 262577083,
    "status": "Tidak Aktif"
  },
  {
    "id": "0a5b56f9-0bd4-48ec-bb8c-3a36701ac9eb",
    "nama": "Koperasi Mitra Bahari",
    "lokasi": "Balikpapan, Kalimantan Timur",
    "ketua": "Rahmat Hidayat",
    "jumlahAnggota": 136,
    "volumeKg": 5258,
    "nilaiTransaksi": 177643811,
    "status": "Tidak Aktif"
  },
  {
    "id": "51b40a3a-8fc7-4f48-ba7a-ceffd365a187",
    "nama": "Koperasi Nusa Bahari",
    "lokasi": "Kupang, Nusa Tenggara Timur",
    "ketua": "Yohanes Bili",
    "jumlahAnggota": 96,
    "volumeKg": 9123,
    "nilaiTransaksi": 384023461,
    "status": "Aktif"
  },
  {
    "id": "e7491516-ee74-41c3-9870-135597e47bc0",
    "nama": "Koperasi Papua Bahari",
    "lokasi": "Sorong, Papua Barat Daya",
    "ketua": "Yustus Kaisiepo",
    "jumlahAnggota": 197,
    "volumeKg": 1677,
    "nilaiTransaksi": 239705971,
    "status": "Aktif"
  },
  {
    "id": "f959725d-08ed-4a0e-97fe-ec71108ab31a",
    "nama": "Koperasi Lombok Bahari",
    "lokasi": "Mataram, Nusa Tenggara Barat",
    "ketua": "Lalu Wirawan",
    "jumlahAnggota": 75,
    "volumeKg": 6839,
    "nilaiTransaksi": 212404034,
    "status": "Tidak Aktif"
  },
  {
    "id": "6d004557-fbe6-44d8-9379-0c0865dc908a",
    "nama": "Koperasi Teluk Palu Sejahtera",
    "lokasi": "Palu, Sulawesi Tengah",
    "ketua": "Muhammad Yusri",
    "jumlahAnggota": 223,
    "volumeKg": 8175,
    "nilaiTransaksi": 145631781,
    "status": "Aktif"
  }
];
