// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { Notifikasi } from '../types';

export const notifikasiData: Notifikasi[] = [
  {
    "id": "88d64380-34b2-4fd2-acef-1014c7717bf0",
    "jenis": "sistem",
    "judul": "Sinkronisasi Data Selesai",
    "deskripsi": "Sinkronisasi data kapal dan nelayan telah selesai.",
    "waktu": "2025-05-06T05:34:42.628Z",
    "dibaca": false
  },
  {
    "id": "0f45f782-f4a3-45cb-b3bd-00280579ed2e",
    "jenis": "sistem",
    "judul": "Pemeliharaan Terjadwal",
    "deskripsi": "Pemeliharaan sistem akan dilakukan pada dini hari.",
    "waktu": "2025-05-07T14:46:43.406Z",
    "dibaca": true
  },
  {
    "id": "c033c33c-17c9-4efb-975c-6206ead4ac7e",
    "jenis": "peringatan",
    "judul": "Cuaca Buruk",
    "deskripsi": "Waspada gelombang tinggi di perairan Laut Sulawesi.",
    "waktu": "2025-05-06T01:44:08.106Z",
    "dibaca": false
  },
  {
    "id": "147536a6-92e0-4f8b-ab5b-57920b2f6831",
    "jenis": "informasi",
    "judul": "Anggota Koperasi Baru",
    "deskripsi": "Nelayan baru telah bergabung dengan Koperasi Bahari Minang.",
    "waktu": "2025-05-09T14:10:40.383Z",
    "dibaca": true
  },
  {
    "id": "f523af7d-aaa5-4473-9b93-57cfe9e53442",
    "jenis": "sukses",
    "judul": "Data Nelayan Terverifikasi",
    "deskripsi": "Data nelayan baru telah berhasil diverifikasi.",
    "waktu": "2025-05-09T18:32:11.085Z",
    "dibaca": true
  },
  {
    "id": "0c61b762-74d3-476d-ab05-244d97d8b0e7",
    "jenis": "informasi",
    "judul": "Kapal Sandar",
    "deskripsi": "KM. Mina Persada telah sandar di PPI Banyuwangi.",
    "waktu": "2025-05-06T00:54:52.332Z",
    "dibaca": true
  },
  {
    "id": "abac7f6c-355f-484e-a568-41ce98c3c93f",
    "jenis": "sistem",
    "judul": "Sinkronisasi Data Selesai",
    "deskripsi": "Sinkronisasi data kapal dan nelayan telah selesai.",
    "waktu": "2025-05-08T06:11:14.515Z",
    "dibaca": true
  },
  {
    "id": "e61ddb1d-6aa5-4934-b908-5216c9ae88d2",
    "jenis": "sistem",
    "judul": "Sinkronisasi Data Selesai",
    "deskripsi": "Sinkronisasi data kapal dan nelayan telah selesai.",
    "waktu": "2025-05-07T15:49:09.505Z",
    "dibaca": true
  },
  {
    "id": "35ea90ed-2bfe-4a13-a322-cee9fcd231db",
    "jenis": "sistem",
    "judul": "Pembaruan Sistem",
    "deskripsi": "Sistem berhasil diperbarui ke versi terbaru.",
    "waktu": "2025-05-08T03:06:08.925Z",
    "dibaca": true
  },
  {
    "id": "d84b9a31-d112-4084-bd27-bb5403cc726f",
    "jenis": "informasi",
    "judul": "Anggota Koperasi Baru",
    "deskripsi": "Nelayan baru telah bergabung dengan Koperasi Harapan Baru.",
    "waktu": "2025-05-05T22:55:01.384Z",
    "dibaca": false
  },
  {
    "id": "b52400fd-e284-4205-a31e-23cfa1100a62",
    "jenis": "sukses",
    "judul": "Tiket Bantuan Selesai",
    "deskripsi": "Tiket dukungan Anda telah ditandai selesai.",
    "waktu": "2025-05-05T23:28:56.043Z",
    "dibaca": true
  },
  {
    "id": "498c0e07-8e8e-46bb-9e0a-f47c70eb2b91",
    "jenis": "sistem",
    "judul": "Pembaruan Sistem",
    "deskripsi": "Sistem berhasil diperbarui ke versi terbaru.",
    "waktu": "2025-05-07T08:32:02.852Z",
    "dibaca": true
  },
  {
    "id": "3b06d634-f923-4a00-abe9-dc1788338c6d",
    "jenis": "informasi",
    "judul": "Kapal Sandar",
    "deskripsi": "KM. Putra Samudra telah sandar di TPI Surabaya.",
    "waktu": "2025-05-08T19:51:46.063Z",
    "dibaca": false
  },
  {
    "id": "08f1d84d-440e-4581-9644-d8c33cbc8693",
    "jenis": "informasi",
    "judul": "Kapal Sandar",
    "deskripsi": "KM. Sumber Jaya telah sandar di TPI Surabaya.",
    "waktu": "2025-05-08T18:31:14.130Z",
    "dibaca": true
  },
  {
    "id": "da97f060-1305-492e-a947-2eb195efa4bd",
    "jenis": "sukses",
    "judul": "Data Nelayan Terverifikasi",
    "deskripsi": "Data nelayan baru telah berhasil diverifikasi.",
    "waktu": "2025-05-08T07:32:28.429Z",
    "dibaca": true
  },
  {
    "id": "a9b78f3d-1b59-451c-8937-c586dfb4a20e",
    "jenis": "peringatan",
    "judul": "Dokumen Kapal Akan Kedaluwarsa",
    "deskripsi": "SLO KM. Berkah Persada akan berakhir dalam 5 hari.",
    "waktu": "2025-05-09T16:54:05.328Z",
    "dibaca": true
  },
  {
    "id": "dd1e8ee5-fe92-42e3-afce-b7f99acec374",
    "jenis": "informasi",
    "judul": "Kapal Masuk Zona Penangkapan",
    "deskripsi": "KM. Anugerah Rejeki memasuki zona penangkapan.",
    "waktu": "2025-05-05T08:47:05.672Z",
    "dibaca": false
  },
  {
    "id": "b36a7e16-5027-4c9c-a621-a30bc67f85ae",
    "jenis": "sistem",
    "judul": "Sinkronisasi Data Selesai",
    "deskripsi": "Sinkronisasi data kapal dan nelayan telah selesai.",
    "waktu": "2025-05-09T13:34:24.701Z",
    "dibaca": false
  },
  {
    "id": "85f73fd4-a958-4af5-81fa-345b43a959e5",
    "jenis": "sukses",
    "judul": "Pemeriksaan Biosecurity Lolos",
    "deskripsi": "KM. Sumber Jaya dinyatakan lolos pemeriksaan biosecurity.",
    "waktu": "2025-05-09T13:44:52.462Z",
    "dibaca": false
  },
  {
    "id": "25fa0259-bbf4-4dd2-b08c-f1f8b971d460",
    "jenis": "sukses",
    "judul": "Data Nelayan Terverifikasi",
    "deskripsi": "Data nelayan baru telah berhasil diverifikasi.",
    "waktu": "2025-05-05T22:08:02.740Z",
    "dibaca": false
  }
];
