// Generated by scripts/seed-mock-data.ts — do not edit by hand.
export const notifikasiData = [
  {
    "id": "d3c4525a-ef40-407e-929b-37375096f0a3",
    "jenis": "sistem",
    "judul": "Tantillus decor abscido annus.",
    "deskripsi": "Cilicium patrocinor aut mollitia patruus cometes theatrum artificiose comparo celo.",
    "waktu": "2026-08-04T21:40:17.607Z",
    "dibaca": false
  },
  {
    "id": "d17e8b09-7cdb-45eb-b519-2ccadae8a265",
    "jenis": "sukses",
    "judul": "Speculum tam caries amor.",
    "deskripsi": "Tondeo tui carmen vita aut nemo vesco curriculum commodi talis.",
    "waktu": "2026-08-06T15:21:49.153Z",
    "dibaca": true
  },
  {
    "id": "cf2b6ce5-75f0-4c89-b91b-d652093b5fe1",
    "jenis": "sistem",
    "judul": "Adopto odit coma aperiam.",
    "deskripsi": "Tendo tepidus color taedium alii assumenda speciosus abbas coniuratio terra.",
    "waktu": "2026-08-07T09:07:39.212Z",
    "dibaca": false
  },
  {
    "id": "11d325dc-8abd-4dfc-ac9a-771d91d9383c",
    "jenis": "sukses",
    "judul": "Bibo perspiciatis apto acerbitas.",
    "deskripsi": "Victus vero eligendi confugo aspernatur ambulo colo tres umbra timidus.",
    "waktu": "2026-08-03T07:22:07.375Z",
    "dibaca": false
  },
  {
    "id": "2eea86e8-89bd-4392-b6fe-7d13009dc61b",
    "jenis": "peringatan",
    "judul": "Voluptatem id praesentium admitto.",
    "deskripsi": "Cunctatio tonsor curto thermae acerbitas dolor cur congregatio amicitia unus.",
    "waktu": "2026-08-05T11:25:31.137Z",
    "dibaca": true
  },
  {
    "id": "1fef9139-acb5-4781-95af-c559a680ea63",
    "jenis": "sukses",
    "judul": "Cohibeo quo supra subiungo.",
    "deskripsi": "Carpo defero amor adhaero deinde defero amplus clarus attero vapulus.",
    "waktu": "2026-08-04T20:14:54.473Z",
    "dibaca": false
  },
  {
    "id": "d9c59f3d-a1fd-41c3-99a0-7e53cd0b0335",
    "jenis": "sistem",
    "judul": "Vorago corroboro suadeo eum.",
    "deskripsi": "Arbitro terebro anser suppellex animus doloribus derelinquo tam undique ambitus.",
    "waktu": "2026-08-05T15:27:22.826Z",
    "dibaca": true
  },
  {
    "id": "cb6fb486-9002-4139-b155-9b70c43e1382",
    "jenis": "sistem",
    "judul": "Damnatio assumenda ventosus tibi.",
    "deskripsi": "Cohors vindico crebro voluptatibus teneo dolorem terga conicio altus super.",
    "waktu": "2026-08-04T01:05:48.174Z",
    "dibaca": false
  },
  {
    "id": "4a6bba00-99a0-4133-bba0-f5418dd3c0c1",
    "jenis": "sistem",
    "judul": "Caecus deludo constans adeptio.",
    "deskripsi": "Cubicularis solio celo comminor mollitia assentator voluptas adversus advoco depereo.",
    "waktu": "2026-08-06T18:46:04.282Z",
    "dibaca": true
  },
  {
    "id": "e09fd98d-ef23-4725-8d8d-66e5d12ecb34",
    "jenis": "peringatan",
    "judul": "Agnosco amoveo nam blandior.",
    "deskripsi": "Amita agnosco ago magnam illum eum suasoria sui crinis victus.",
    "waktu": "2026-08-05T03:25:49.082Z",
    "dibaca": false
  },
  {
    "id": "efd57104-c17f-49cd-93c3-0ff6a5a304a3",
    "jenis": "sistem",
    "judul": "Cohaero comprehendo vel cogo.",
    "deskripsi": "Quaerat tergum demum cotidie ustulo turpis sulum angelus vacuus ad.",
    "waktu": "2026-08-06T23:07:46.347Z",
    "dibaca": false
  },
  {
    "id": "91b0b98c-845e-4390-81ec-7a77acd59f5a",
    "jenis": "sukses",
    "judul": "Ustulo comedo sulum omnis.",
    "deskripsi": "Iure autus tamdiu et usque undique solus carcer cerno ait.",
    "waktu": "2026-08-03T11:16:25.283Z",
    "dibaca": false
  },
  {
    "id": "90e9f087-28e6-4260-bad4-a3a74d33090d",
    "jenis": "sukses",
    "judul": "Summisse argumentum comparo bonus.",
    "deskripsi": "Summisse aeger tunc casus averto denique uberrime celer amplus sub.",
    "waktu": "2026-08-03T05:13:31.202Z",
    "dibaca": false
  },
  {
    "id": "4992d4b1-513f-413e-bdd1-9dcad2f64230",
    "jenis": "peringatan",
    "judul": "Animi catena turpis sint.",
    "deskripsi": "Neque ultra vinitor utpote texo vitae commodi contabesco vomito coaegresco.",
    "waktu": "2026-08-06T17:19:47.371Z",
    "dibaca": true
  },
  {
    "id": "63ebba93-3358-4849-934d-16be63249214",
    "jenis": "informasi",
    "judul": "Coaegresco varietas animi cognatus.",
    "deskripsi": "Tergo adhaero tergum aestus vulgus cerno allatus illum turbo demulceo.",
    "waktu": "2026-08-04T06:39:52.858Z",
    "dibaca": false
  },
  {
    "id": "f8bef4dd-d666-4eac-91df-355f28a6d774",
    "jenis": "informasi",
    "judul": "Trans supra inventore victoria.",
    "deskripsi": "Bis carus odit verto corrigo ocer ambulo advoco quibusdam iure.",
    "waktu": "2026-08-07T06:14:41.784Z",
    "dibaca": true
  },
  {
    "id": "05385e7c-903f-4e43-9879-e9a64f5492b9",
    "jenis": "sistem",
    "judul": "Tolero numquam quae artificiose.",
    "deskripsi": "Aperio vinco cimentarius adulatio adstringo ocer clam audacia natus una.",
    "waktu": "2026-08-04T02:36:19.037Z",
    "dibaca": false
  },
  {
    "id": "7fb62477-8e14-4b26-bf5c-b9841be6ebd5",
    "jenis": "informasi",
    "judul": "Caste tero arx tollo.",
    "deskripsi": "Virtus ullus dicta tempore depopulo deporto arca traho addo taedium.",
    "waktu": "2026-08-05T11:55:15.086Z",
    "dibaca": false
  },
  {
    "id": "ebc22aff-a270-47c9-b8ee-4123b8536df9",
    "jenis": "peringatan",
    "judul": "Ademptio brevis vehemens vulgus.",
    "deskripsi": "Unus veniam solio denuncio ubi crux alter culpo speciosus caterva.",
    "waktu": "2026-08-03T01:29:37.018Z",
    "dibaca": true
  },
  {
    "id": "2748ba1e-f619-4b94-80f8-aafe13b641ce",
    "jenis": "peringatan",
    "judul": "Audax comprehendo beatae una.",
    "deskripsi": "Vicissitudo uberrime tredecim summopere viridis beatus textus solitudo caute eius.",
    "waktu": "2026-08-04T03:49:55.112Z",
    "dibaca": true
  }
] as const;
