// Generated by scripts/seed-mock-data.ts — do not edit by hand.
export const pasarIndustriData = [
  {
    "id": "2eb36654-c5cc-45ac-999e-0c0a70d7b81a",
    "nama": "Pasar Ikan Oakland",
    "jenis": "Pasar Modern",
    "lokasi": "Roobhaven, New Hampshire",
    "pengelola": "Lakin - Aufderhar",
    "volumeKg": 12682,
    "nilaiTransaksi": 582059153,
    "status": "Tidak Aktif"
  },
  {
    "id": "f4d7ba68-83d7-4638-8d40-f5b65e4ec57e",
    "nama": "Pasar Ikan Lake Monserratefurt",
    "jenis": "Pasar Modern",
    "lokasi": "Casperborough, Hawaii",
    "pengelola": "Lynch Inc",
    "volumeKg": 6230,
    "nilaiTransaksi": 630495007,
    "status": "Aktif"
  },
  {
    "id": "d61930b2-ea06-45b0-a0c1-f5c44d5dff42",
    "nama": "Pasar Ikan Port Damon",
    "jenis": "Pasar Modern",
    "lokasi": "Lisashire, Maine",
    "pengelola": "Emard Group",
    "volumeKg": 3116,
    "nilaiTransaksi": 410742694,
    "status": "Tidak Aktif"
  },
  {
    "id": "ea4d991d-6228-4679-aa65-c8f777db162b",
    "nama": "Pasar Ikan Sierra Vista",
    "jenis": "Pasar Modern",
    "lokasi": "Eugeneberg, Maine",
    "pengelola": "Brown-Wolff Inc",
    "volumeKg": 13682,
    "nilaiTransaksi": 783068339,
    "status": "Aktif"
  },
  {
    "id": "a8c1e0fc-fc89-4147-8b44-d953db48be8f",
    "nama": "Pasar Ikan Harrisburg",
    "jenis": "Pasar Modern",
    "lokasi": "Angustown, Ohio",
    "pengelola": "Gutkowski, Toy and Vandervort-Bode",
    "volumeKg": 16518,
    "nilaiTransaksi": 276442195,
    "status": "Tidak Aktif"
  },
  {
    "id": "992b2378-f82b-415f-b0e0-5eaf922685cb",
    "nama": "Pasar Ikan San Francisco",
    "jenis": "Pasar Tradisional",
    "lokasi": "East Donniestad, Nevada",
    "pengelola": "Weber, Lebsack and Beer",
    "volumeKg": 10036,
    "nilaiTransaksi": 540973303,
    "status": "Aktif"
  },
  {
    "id": "97b0f238-2cc4-4b78-b1bf-c55f4c62f8fe",
    "nama": "Pasar Ikan Bernhardstead",
    "jenis": "Pasar Tradisional",
    "lokasi": "East Kolbyboro, Nevada",
    "pengelola": "Schaden, Bahringer-Gislason and Boyle",
    "volumeKg": 10325,
    "nilaiTransaksi": 168796765,
    "status": "Aktif"
  },
  {
    "id": "81414e60-c9b9-4a4c-8c76-999a144e3a6d",
    "nama": "Pasar Ikan West Miranda",
    "jenis": "Pasar Modern",
    "lokasi": "Lake Constantin, Hawaii",
    "pengelola": "Towne - Okuneva",
    "volumeKg": 15242,
    "nilaiTransaksi": 247128897,
    "status": "Aktif"
  },
  {
    "id": "9baf79d0-ee50-42b2-bc5a-f6d936eac1ed",
    "nama": "Pasar Ikan East Queen",
    "jenis": "Pasar Tradisional",
    "lokasi": "Madelynhaven, New Mexico",
    "pengelola": "Ledner, Hudson and Stoltenberg",
    "volumeKg": 14500,
    "nilaiTransaksi": 548792799,
    "status": "Aktif"
  },
  {
    "id": "81ae512d-8c48-4ce6-bf19-489b9ee3022f",
    "nama": "Pasar Ikan Port Jewelton",
    "jenis": "Industri Pengolahan",
    "lokasi": "Lake Marcelcester, Missouri",
    "pengelola": "Hilpert Group",
    "volumeKg": 2224,
    "nilaiTransaksi": 296457556,
    "status": "Tidak Aktif"
  },
  {
    "id": "dff8b17a-24a0-4ba5-be29-a7b941974a4c",
    "nama": "Pasar Ikan Gerholdchester",
    "jenis": "Pasar Modern",
    "lokasi": "West Bernardview, Maryland",
    "pengelola": "Halvorson LLC",
    "volumeKg": 14604,
    "nilaiTransaksi": 769338026,
    "status": "Aktif"
  },
  {
    "id": "9abd3d9b-190e-407e-95ae-370fe56bd1b9",
    "nama": "Pasar Ikan Green Bay",
    "jenis": "Industri Pengolahan",
    "lokasi": "Izabellashire, Connecticut",
    "pengelola": "Barton Inc",
    "volumeKg": 7250,
    "nilaiTransaksi": 403538953,
    "status": "Tidak Aktif"
  }
] as const;
