// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { PasarIndustri } from '../types';

export const pasarIndustriData: PasarIndustri[] = [
  {
    "id": "e22003ab-9fa6-4bca-8052-3054a57f1185",
    "nama": "Pasar Ikan Muara Baru",
    "jenis": "Pasar Tradisional",
    "lokasi": "Jakarta Utara, DKI Jakarta",
    "pengelola": "Perumda Pasar Jaya",
    "volumeKg": 15027,
    "nilaiTransaksi": 175887759,
    "status": "Aktif"
  },
  {
    "id": "3c7ef3a0-3808-4591-8a34-18b9b479e0ea",
    "nama": "Pasar Ikan Modern BSD",
    "jenis": "Pasar Tradisional",
    "lokasi": "Tangerang Selatan, Banten",
    "pengelola": "PT. Modern Market",
    "volumeKg": 4031,
    "nilaiTransaksi": 346678532,
    "status": "Aktif"
  },
  {
    "id": "46b5e421-be05-447b-bf6e-e1b8312916d0",
    "nama": "Pasar Ikan Modern Kenjeran",
    "jenis": "Industri Pengolahan",
    "lokasi": "Surabaya, Jawa Timur",
    "pengelola": "PT. Bahari Sejahtera",
    "volumeKg": 10533,
    "nilaiTransaksi": 753448914,
    "status": "Tidak Aktif"
  },
  {
    "id": "3e3f0e52-f5a6-45a3-94a8-9cfb316c7c63",
    "nama": "Pasar Ikan Jembatan Puri",
    "jenis": "Pasar Modern",
    "lokasi": "Jakarta Barat, DKI Jakarta",
    "pengelola": "Perumda Pasar Jaya",
    "volumeKg": 10589,
    "nilaiTransaksi": 741796695,
    "status": "Tidak Aktif"
  },
  {
    "id": "812dd08b-6487-44ef-a675-06c0c0c66e61",
    "nama": "Pasar Ikan Modern Semarang",
    "jenis": "Pasar Tradisional",
    "lokasi": "Semarang, Jawa Tengah",
    "pengelola": "PT. Samudra Food",
    "volumeKg": 10236,
    "nilaiTransaksi": 682610196,
    "status": "Aktif"
  },
  {
    "id": "f4916d4f-2620-4a8f-8dd3-9b4b4fbfd756",
    "nama": "Pasar Ikan Kedonganan",
    "jenis": "Industri Pengolahan",
    "lokasi": "Badung, Bali",
    "pengelola": "UPTD Pasar Badung",
    "volumeKg": 10476,
    "nilaiTransaksi": 170856589,
    "status": "Aktif"
  },
  {
    "id": "0cf18ec6-f145-4569-8bcb-89439ef4529a",
    "nama": "Pasar Ikan Paotere",
    "jenis": "Industri Pengolahan",
    "lokasi": "Makassar, Sulawesi Selatan",
    "pengelola": "PT. Nusantara Canning",
    "volumeKg": 5419,
    "nilaiTransaksi": 384600759,
    "status": "Tidak Aktif"
  },
  {
    "id": "306b554c-3865-413d-8a61-807224e1c93c",
    "nama": "Pasar Ikan Higienis Bandung",
    "jenis": "Pasar Tradisional",
    "lokasi": "Bandung, Jawa Barat",
    "pengelola": "PD Pasar Bermartabat",
    "volumeKg": 11104,
    "nilaiTransaksi": 91962786,
    "status": "Aktif"
  },
  {
    "id": "07d2fc26-199e-4c4b-af7b-0d141802e868",
    "nama": "Pasar Ikan Belawan",
    "jenis": "Pasar Modern",
    "lokasi": "Medan, Sumatera Utara",
    "pengelola": "PT. Belawan Bahari Nusantara",
    "volumeKg": 11901,
    "nilaiTransaksi": 457042449,
    "status": "Aktif"
  },
  {
    "id": "7df1e353-7136-4c70-99dc-310e65cfeb5f",
    "nama": "Industri Pengolahan Ikan Musi Jaya",
    "jenis": "Industri Pengolahan",
    "lokasi": "Palembang, Sumatera Selatan",
    "pengelola": "PT. Musi Jaya Perikanan",
    "volumeKg": 15518,
    "nilaiTransaksi": 209679629,
    "status": "Aktif"
  },
  {
    "id": "3dffbf4f-ccfd-4e34-9e20-87a42a8ba46f",
    "nama": "Pasar Ikan Modern Banjarmasin",
    "jenis": "Industri Pengolahan",
    "lokasi": "Banjarmasin, Kalimantan Selatan",
    "pengelola": "PT. Banjar Mina Sejahtera",
    "volumeKg": 14432,
    "nilaiTransaksi": 545116483,
    "status": "Aktif"
  },
  {
    "id": "857f313e-5652-4c46-8502-b860b62ebece",
    "nama": "Industri Pengolahan Ikan Manado Jaya",
    "jenis": "Industri Pengolahan",
    "lokasi": "Manado, Sulawesi Utara",
    "pengelola": "PT. Manado Bahari Lestari",
    "volumeKg": 19901,
    "nilaiTransaksi": 663412477,
    "status": "Aktif"
  }
];
