// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { PasarIndustri } from '../types';

export const pasarIndustriData: PasarIndustri[] = [
  {
    "id": "9e0ea241-5a46-4b5e-a421-be0547bf6ee1",
    "nama": "Pasar Ikan Muara Baru",
    "jenis": "Pasar Modern",
    "lokasi": "Jakarta Utara, DKI Jakarta",
    "pengelola": "Perumda Pasar Jaya",
    "volumeKg": 5580,
    "nilaiTransaksi": 156868244,
    "status": "Aktif"
  },
  {
    "id": "916d0ec7-ef3e-43f0-be52-f5a65a34a89c",
    "nama": "Pasar Ikan Modern BSD",
    "jenis": "Industri Pengolahan",
    "lokasi": "Tangerang Selatan, Banten",
    "pengelola": "PT. Modern Market",
    "volumeKg": 6340,
    "nilaiTransaksi": 132780829,
    "status": "Aktif"
  },
  {
    "id": "c7c63787-ec81-42dd-b08b-64874ef67506",
    "nama": "Pasar Ikan Modern Kenjeran",
    "jenis": "Pasar Tradisional",
    "lokasi": "Surabaya, Jawa Timur",
    "pengelola": "PT. Bahari Sejahtera",
    "volumeKg": 15745,
    "nilaiTransaksi": 96446032,
    "status": "Tidak Aktif"
  },
  {
    "id": "66e61b07-d4f4-4916-9d4f-2620a8fdd39b",
    "nama": "Pasar Ikan Jembatan Puri",
    "jenis": "Industri Pengolahan",
    "lokasi": "Jakarta Barat, DKI Jakarta",
    "pengelola": "Perumda Pasar Jaya",
    "volumeKg": 6615,
    "nilaiTransaksi": 769497829,
    "status": "Tidak Aktif"
  },
  {
    "id": "fd7562d7-230c-4f18-9ec6-f145569bcb89",
    "nama": "Pasar Ikan Modern Semarang",
    "jenis": "Pasar Tradisional",
    "lokasi": "Semarang, Jawa Tengah",
    "pengelola": "PT. Samudra Food",
    "volumeKg": 12223,
    "nilaiTransaksi": 745027235,
    "status": "Tidak Aktif"
  },
  {
    "id": "4529a2f3-6f30-46b5-954c-386513da6180",
    "nama": "Pasar Ikan Kedonganan",
    "jenis": "Pasar Tradisional",
    "lokasi": "Badung, Bali",
    "pengelola": "UPTD Pasar Badung",
    "volumeKg": 4679,
    "nilaiTransaksi": 278417408,
    "status": "Tidak Aktif"
  },
  {
    "id": "1c93c348-0507-4d2f-8c26-199ec4bf7b0d",
    "nama": "Pasar Ikan Paotere",
    "jenis": "Pasar Tradisional",
    "lokasi": "Makassar, Sulawesi Selatan",
    "pengelola": "PT. Nusantara Canning",
    "volumeKg": 4172,
    "nilaiTransaksi": 457312865,
    "status": "Aktif"
  },
  {
    "id": "2e868b78-847d-4f1e-8353-7136c709dc31",
    "nama": "Pasar Ikan Higienis Bandung",
    "jenis": "Industri Pengolahan",
    "lokasi": "Bandung, Jawa Barat",
    "pengelola": "PD Pasar Bermartabat",
    "volumeKg": 9115,
    "nilaiTransaksi": 336509312,
    "status": "Tidak Aktif"
  },
  {
    "id": "feb5f4ec-273d-4ffb-af4f-ccfde34e2087",
    "nama": "Pasar Ikan Belawan",
    "jenis": "Pasar Tradisional",
    "lokasi": "Medan, Sumatera Utara",
    "pengelola": "PT. Belawan Bahari Nusantara",
    "volumeKg": 4433,
    "nilaiTransaksi": 571970635,
    "status": "Aktif"
  },
  {
    "id": "ba46f7eb-a785-47f3-913e-5652c46502b8",
    "nama": "Industri Pengolahan Ikan Musi Jaya",
    "jenis": "Pasar Tradisional",
    "lokasi": "Palembang, Sumatera Selatan",
    "pengelola": "PT. Musi Jaya Perikanan",
    "volumeKg": 14760,
    "nilaiTransaksi": 360251835,
    "status": "Aktif"
  },
  {
    "id": "ebece2ff-c843-4042-b76e-c7537c31a7c1",
    "nama": "Pasar Ikan Modern Banjarmasin",
    "jenis": "Industri Pengolahan",
    "lokasi": "Banjarmasin, Kalimantan Selatan",
    "pengelola": "PT. Banjar Mina Sejahtera",
    "volumeKg": 19646,
    "nilaiTransaksi": 291583253,
    "status": "Aktif"
  },
  {
    "id": "1158fa50-71bd-4a45-9bfd-5ec58f97b278",
    "nama": "Industri Pengolahan Ikan Manado Jaya",
    "jenis": "Pasar Tradisional",
    "lokasi": "Manado, Sulawesi Utara",
    "pengelola": "PT. Manado Bahari Lestari",
    "volumeKg": 12774,
    "nilaiTransaksi": 267143596,
    "status": "Tidak Aktif"
  }
];
