// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { TiketBantuan } from '../types';

export const tiketBantuanData: TiketBantuan[] = [
  {
    "id": "1a8f9226-f53a-4ce3-8127-44203a210a80",
    "judul": "Permintaan penambahan akun pengguna",
    "kategori": "Akun",
    "deskripsi": "Mohon dibuatkan akun tambahan untuk petugas lapangan di pelabuhan.",
    "status": "Terbuka",
    "dibuatPada": "2025-04-30T01:42:31.778Z"
  },
  {
    "id": "08421d89-8b4d-43c4-9525-aef4007e29b3",
    "judul": "Permintaan akses unduh laporan",
    "kategori": "Data",
    "deskripsi": "Mohon diberikan akses untuk mengunduh laporan bulanan pada menu Laporan & Analitik.",
    "status": "Terbuka",
    "dibuatPada": "2025-04-29T12:07:11.510Z"
  },
  {
    "id": "96f0a36c-c701-4493-8995-c2547dd17e8b",
    "judul": "Permintaan reset kata sandi akun",
    "kategori": "Akun",
    "deskripsi": "Saya lupa kata sandi akun dan membutuhkan bantuan untuk mengatur ulang.",
    "status": "Diproses",
    "dibuatPada": "2025-04-28T19:40:13.930Z"
  },
  {
    "id": "b5eb5192-ccad-4ae8-aa26-5daab31cd3f3",
    "judul": "Pertanyaan terkait kebijakan data",
    "kategori": "Lainnya",
    "deskripsi": "Ingin menanyakan kebijakan penyimpanan data nelayan pada sistem ini.",
    "status": "Selesai",
    "dibuatPada": "2025-04-28T11:38:20.173Z"
  },
  {
    "id": "c2cf2b6c-e575-4f0c-b899-1bd652093b5f",
    "judul": "Permintaan penambahan akun pengguna",
    "kategori": "Akun",
    "deskripsi": "Mohon dibuatkan akun tambahan untuk petugas lapangan di pelabuhan.",
    "status": "Terbuka",
    "dibuatPada": "2025-05-05T22:57:27.424Z"
  },
  {
    "id": "952cc4b1-2a05-4cf8-b11d-325dc8abddfc",
    "judul": "Permintaan penambahan menu cuaca",
    "kategori": "Lainnya",
    "deskripsi": "Mohon dipertimbangkan penambahan menu khusus untuk rekap cuaca harian.",
    "status": "Diproses",
    "dibuatPada": "2025-05-02T23:24:19.761Z"
  }
];
