// Generated by scripts/seed-mock-data.ts — do not edit by hand.
import type { TiketBantuan } from '../types';

export const tiketBantuanData: TiketBantuan[] = [
  {
    "id": "abddfcc9-a771-4d91-9d93-83cb83920ee8",
    "judul": "Ambulo colo tres umbra.",
    "kategori": "Lainnya",
    "deskripsi": "Sumptus attollo utroque utrimque. Ducimus cubo vaco hic illum paens supra turbo.",
    "status": "Terbuka",
    "dibuatPada": "2025-05-01T21:55:11.800Z"
  },
  {
    "id": "26fe7d13-009d-4c61-8bd3-f8906d6c0865",
    "judul": "Minus conscendo altus vulticulus vapulus vindico praesentium aliquam.",
    "kategori": "Teknis",
    "deskripsi": "Quibusdam tersus supplanto conturbo decet ipsum aestas. Socius vorago tempore concedo contra.",
    "status": "Diproses",
    "dibuatPada": "2025-05-02T15:42:04.860Z"
  },
  {
    "id": "680ea637-a4ab-4b37-b107-7142e7fd9c59",
    "judul": "Trans repellendus alo vinculum tutis.",
    "kategori": "Teknis",
    "deskripsi": "Beneficium quae stabilis acervus dedico vicissitudo conatus bos terror. Accusantium sum adiuvo caries aureus congregatio casus usus vorago.",
    "status": "Diproses",
    "dibuatPada": "2025-05-03T20:29:58.938Z"
  },
  {
    "id": "82c1b187-bd19-42cb-96fb-486900213915",
    "judul": "Surculus depereo acervus temperantia claustrum bis.",
    "kategori": "Lainnya",
    "deskripsi": "Caput distinctio appello. Vivo damnatio assumenda ventosus tibi cohors vindico crebro voluptatibus.",
    "status": "Selesai",
    "dibuatPada": "2025-04-30T05:16:16.455Z"
  },
  {
    "id": "c51b484a-6bba-4009-b9a0-133ba0f5418d",
    "judul": "Tero absque textus aiunt tenuis.",
    "kategori": "Lainnya",
    "deskripsi": "Deludo constans adeptio cubicularis. Celo comminor mollitia assentator voluptas adversus advoco depereo.",
    "status": "Selesai",
    "dibuatPada": "2025-04-26T19:07:22.785Z"
  },
  {
    "id": "e09fd98d-ef23-4725-8d8d-66e5d12ecb34",
    "judul": "Agnosco amoveo nam blandior amita.",
    "kategori": "Teknis",
    "deskripsi": "Magnam illum eum. Sui crinis victus desipio soleo vapulus volaticus urbs.",
    "status": "Terbuka",
    "dibuatPada": "2025-04-29T13:39:27.762Z"
  }
];
